items = [
    ("Grand", "adj.", "Lehibe", "De taille importante.", "C'est un grand arbre.", "Kazo lehibe io."),
    ("Petit", "adj.", "Kely", "De faible taille.", "Un petit enfant joue.", "Milalao ny zaza kely."),
    ("Bon", "adj.", "Tsara / Matsiro", "Qui a des qualités positives ou bon goût.", "Ce repas est très bon.", "Tena matsiro ity sakafo ity."),
    ("Mauvais", "adj.", "Ratsy", "Qui manque de qualité.", "C'est un mauvais comportement.", "Fomba ratsy izany."),
    ("Beau", "adj.", "Mendrika / Kanto", "Qui fait plaisir aux yeux.", "Un beau paysage tropical.", "Mendrika kanto ny tanàna."),
    ("Joli", "adj.", "Mendrika kely / Kanto", "Agréable à regarder.", "Une jolie robe fleurie.", "Robe fleurie kanto."),
    ("Nouveau", "adj.", "Vaovao", "Récemment produit ou apparu.", "J'ai acheté un nouveau téléphone.", "Nividy finday vaovao aho."),
    ("Vieux", "adj.", "Efa antitra / Antitra", "Âgé ou ancien.", "Mon grand-père est très vieux.", "Tena antitra ny dadabeko."),
    ("Chaud", "adj.", "Mafana", "Qui a une température élevée.", "Le thé est encore très chaud.", "Mba mafana be ny thé."),
    ("Froid", "adj.", "Mangatsiaka", "Qui a une température basse.", "L'eau de la rivière est froide.", "Mangatsiaka ny rano ao an-dony."),
    ("Rapide", "adj.", "Haingana", "Qui se déplace à grande vitesse.", "Le train express est rapide.", "Haingana ny train express."),
    ("Lent", "adj.", "Monompo kely / Madaitra", "Qui manque de vitesse.", "La tortue est un animal lent.", "Animal madaitra ny tortue."),
    ("Facile", "adj.", "Mora", "Qui ne demande aucun effort.", "Cette leçon de français est facile.", "Mora ity lesona frantsay ity."),
    ("Difficile", "adj.", "Sarotra", "Qui demande beaucoup d'effort.", "Un problème mathématique difficile.", "Olana mathématique sarotra."),
    ("Heureux", "adj.", "Faly", "Qui éprouve du bonheur.", "Je suis heureux de te voir.", "Faly aho mahita anao."),
    ("Triste", "adj.", "Malahelo", "Qui éprouve de la chagrin.", "Pourquoi es-tu triste aujourd'hui ?", "Nahoana ianao no malahelo androany ?"),
    ("Fort", "adj.", "Mavandy / Mafy", "Qui a de la force physique ou morale.", "Un homme fort et courageux.", "Lehilahy mafy sy mahereza."),
    ("Faible", "adj.", "Malemy", "Qui manque de force.", "Après la maladie, il est encore faible.", "Mba malemy izy aorian'ny aretina."),
    ("Propre", "adj.", "Madio", "Exempt de saleté.", "La chambre est bien propre.", "Madio tsara ny efitrano."),
    ("Sale", "adj.", "Ratsy / Maimbo / Maloto", "Qui manque de propreté.", "Lave tes vêtements sales.", "Sasao ny akanjo maloto-nao."),
    ("Riche", "adj.", "Manana / Manan-karena", "Qui possède beaucoup de biens.", "Un homme riche et généreux.", "Lehilahy manan-karena sy tsara fanahy."),
    ("Pauvre", "adj.", "Mahantra", "Qui manque de ressources.", "Aider les personnes pauvres.", "Manampy ny olona mahantra."),
    ("Jeune", "adj.", "Tanora", "Qui n'est pas âgé.", "Une jeune fille dynamique.", "Zazavavy tanora mahafinaritra."),
    ("Ancien", "adj.", "Tranainy", "D'une époque passée.", "Un bâtiment ancien et historique.", "Trano tranainy manana tantara."),
    ("Lourd", "adj.", "Mavandy", "Qui pèse beaucoup.", "Ce sac de riz est très lourd.", "Tena mavandy io gony vary io."),
    ("Léger", "adj.", "Mora indrindra / Maivana", "Qui pèse peu.", "Une plume est très légère.", "Tena maivana ny plume."),
    ("Clair", "adj.", "Mifantsika / Mazava", "Bien éclairé ou compréhensible.", "Une explication très claire.", "Fanazavana mazava be."),
    ("Sombre", "adj.", "Maintso / Maizina", "Obscur ou peu éclairé.", "Une nuit sombre sans lune.", "Alina maizina tsy misy volana."),
    ("Calme", "adj.", "Milamina", "Tranquille et sans bruit.", "Un village très calme.", "Tanàna milamina be."),
    ("Bruyant", "adj.", "Mitabataba", "Qui fait beaucoup de bruit.", "La rue commerçante est bruyante.", "Mitabataba ny lálana fivarotana."),
    ("Doux", "adj.", "Malemy / Mamy", "Agréable au toucher ou goût.", "Une musique douce et apaisante.", "Mozika malemy sy mampangatsiatsiaka."),
    ("Dur", "adj.", "Mafy", "Résistant à la pression.", "Le bois d'ébène est très dur.", "Tena mafy ny kazo ébène."),
    ("Sec", "adj.", "Maina", "Sans humidité.", "Le linge est bien sec.", "Maina tsara ny lamba."),
    ("Mouillé", "adj.", "Mando", "Imbibé d'eau.", "Mes vêtements sont mouillés par la pluie.", "Mando amin'ny orana ny akanjoko."),
    ("Plein", "adj.", "Feno", "Rempli au maximum.", "Le verre est plein d'eau.", "Feno rano ny vera."),
    ("Vide", "adj.", "Gana", "Qui ne contient rien.", "La bouteille est vide.", "Gana ny tavoahangy."),
    ("Cher", "adj.", "Lavitra / Lafo", "De prix élevé.", "Ce manteau est trop cher.", "Lafo loatra ity manteau ity."),
    ("Gratuit", "adj.", "Maimaim-poana", "Qui ne coûte rien.", "L'entrée est gratuite pour les enfants.", "Maimaim-poana ny fidirana ho an'ny ankizy."),
    ("Vrai", "adj.", "Marina", "Conforme à la réalité.", "Une histoire vraie et touchante.", "Tantara marina sy mahafinaritra."),
    ("Faux", "adj.", "Diso", "Non conforme à la vérité.", "C'est une fausse information.", "Vaovao diso izany.")
]
