items = [
    ("Ville", "n.f.", "Tànana / Tanàn-dehibe", "Agglomération urbaine importante.", "Antananarivo est la capitale.", "Antananarivo no renivohitra."),
    ("Village", "n.m.", "Tanàna kely / Ambanivohitra", "Petite agglomération rurale.", "Mon village est calme.", "Milamina ny tanànako."),
    ("Rue", "n.f.", "Lálana", "Voie bordée de maisons en ville.", "La rue est animée.", "Manana aina ny lálana."),
    ("Banque", "n.f.", "Banky", "Établissement financier.", "La banque ouvre à huit heures.", "Misokatra amin me valo ora ny banky."),
    ("Poste", "n.f.", "Posta", "Service d'acheminement du courrier.", "Je vais envoyer une lettre à la poste.", "Handeha handefa taratasy ao an-posta aho."),
    ("Gare", "n.f.", "Gara", "Lieu d'arrêt des trains ou bus.", "Le bus part de la gare routière.", "Miala ao an-gara ny bus."),
    ("Bus", "n.m.", "Taxibe / Bus", "Véhicule de transport en commun.", "Je prends le bus tous les matins.", "Maka taxibe aho maraina rehetra."),
    ("Taxi", "n.m.", "Taxi", "Voiture de transport payant.", "Appelez un taxi pour aller à l'aéroport.", "Antsoy ny taxi handeha any an-seranana."),
    ("Avion", "n.m.", "Roplanina / Fiara-manidina", "Appareil volant de transport.", "L'avion décolle à quatorze heures.", "Miala amin'ny folo sy efatra ora ny roplanina."),
    ("Bateau", "n.m.", "Sambo", "Véhicule naviguant sur l'eau.", "Le bateau traverse le canal.", "Mampitaha ny canal ny sambo."),
    ("Vélo", "n.m.", "Bisikileta", "Véhicule à deux roues et pédales.", "Mon frère va à l'école à vélo.", "Mandeha bisikileta any an-tsekoly ny rahalahiko."),
    ("Aéroport", "n.m.", "Seranam-piaramanidina", "Terrain aménagé pour les avions.", "L'aéroport d'Ivato est moderne.", "Maoderina ny seranam-piaramanidina Ivato."),
    ("Pont", "n.m.", "Tetezana", "Ouvrage reliant deux rives.", "Traversez le pont pour entrer en ville.", "Mampitaha ny tetezana hiditra an-tànana."),
    ("Restaurant", "n.m.", "Hotely fisakafoana", "Établissement où l'on sert des repas.", "Ce restaurant propose de bons plats.", "Manolotra sakafo tsara io hotely io."),
    ("Église", "n.f.", "Fiangonana", "Édifice consacré au culte chrétien.", "Les fidèles vont à l'église le dimanche.", "Mandeha any am-piangonana ny mpivavaka amin'ny Alahady."),
    ("Magasin", "n.m.", "Trano fivarotana / Fivarotana", "Lieu où l'on vend des marchandises.", "Le magasin est ouvert toute la journée.", "Misokatra tontolo andro ny fivarotana."),
    ("Boutique", "n.f.", "Boutique / Fivarotana kely", "Petit commerce de détail.", "J'achète du pain à la boutique du coin.", "Mividy mofo ao amin'ny boutique kely aho."),
    ("Place", "n.f.", "Kianja / Toerana", "Espace public découvert en ville.", "La grande place est décorée.", "Nalaina sary ny kianja lehibe."),
    ("Parking", "n.m.", "Toeram-pijanonana fiara", "Lieu aménagé pour stationner.", "Garez la voiture sur le parking.", "Atsaharo amin'ny toeram-pijanonana ny fiara."),
    ("Port", "n.m.", "Seranantsambo", "Lieu aménagé pour les bateaux.", "Le port de Toamasina est le plus grand.", "Lehibe indrindra ny seranantsambo Toamasina."),
    ("Train", "n.m.", "Lamasinina", "Convoi ferroviaire.", "Le train circule sur les rails.", "Mihazakazaka amin'ny lalamby ny lamasinina."),
    ("Ticket", "n.m.", "Tapakila", "Billet d'entrée ou de transport.", "Conservez votre ticket jusqu'à la sortie.", "Atsaharo ny tapakila hatreny amin'ny fivoahana."),
    ("Passager", "n.m.", "Mpiantsambo / Mpandeha", "Personne voyageant dans un transport.", "Les passagers montent à bord.", "Miaka-sambo ny mpandeha."),
    ("Conducteur", "n.m.", "Mpamono / Mpanamory", "Personne qui dirige un véhicule.", "Le conducteur respecte le code de la route.", "Manaja ny lalana ny mpanamory."),
    ("Bagage", "n.m.", "Entana", "Effets emportés en voyage.", "Enregistrez vos bagages au comptoir.", "Ampidiro ao an-tsoratra ny entanao."),
    ("Valise", "n.f.", "Valise / Entana", "Coffre portatif pour vêtements.", "Ma valise est prête pour le départ.", "Vonona amin'ny fiahiana ny valise-ko."),
    ("Carte", "n.f.", "Sarintany", "Représentation géographique.", "Consultez la carte pour trouver l'itinéraire.", "Jereo ny sarintany hahitana ny lálana."),
    ("Camion", "n.m.", "Fiara lehibe / Kamiao", "Grand véhicule de transport de marchandises.", "Le camion transporte du riz.", "Mitondra vary ny kamiao."),
    ("Moto", "n.m.", "Môtô", "Véhicule motorisé à deux roues.", "Il roule à moto avec un casque.", "Mitaingina môtô amin'ny casque izy."),
    ("Taxi-brousse", "n.m.", "Taxi-brousse", "Véhicule reliant les villes régionales.", "Le taxi-brousse part tôt le matin.", "Miala maraina be ny taxi-brousse.")
]
