items = [
    ("Rouge", "adj.", "Mena", "Couleur du sang.", "Elle porte une robe rouge.", "Mano akanjo mena izy."),
    ("Bleu", "adj.", "Manga", "Couleur du ciel dégagé.", "Le ciel est très bleu aujourd'hui.", "Manga be ny lanitra androany."),
    ("Vert", "adj.", "Maitso", "Couleur de l'herbe.", "Les arbres sont bien verts.", "Maitso tsara ny kazo."),
    ("Jaune", "adj.", "Mavo", "Couleur du soleil ou du citron.", "La fleur jaune est très belle.", "Tena kanto ny voninkazo mavo."),
    ("Noir", "adj.", "Maintso / Mainty", "Couleur la plus sombre.", "Il porte des chaussures noires.", "Mano kiraro mainty izy."),
    ("Blanc", "adj.", "Fotsy", "Couleur de la neige ou du lait.", "La chemise blanche est propre.", "Madio ny chemise fotsy."),
    ("Gris", "adj.", "Aparaha / Maintso fotsy", "Couleur intermédiaire entre noir et blanc.", "Le ciel gris annonce la pluie.", "Maneho orana ny lanitra maintso fotsy."),
    ("Marron", "adj.", "Marrina / Maintso tany", "Couleur du bois ou de la terre.", "Il porte une ceinture marron.", "Mano ceinture marron izy."),
    ("Rose", "adj.", "Mena kely / Pink", "Couleur rose bonbon.", "La petite fille aime le rose.", "Tia mena kely ny zazavavy kely."),
    ("Violet", "adj.", "Mviolé / Violet", "Couleur du jus de raisin.", "Les fleurs violettes fleurissent.", "Mamelana ny voninkazo violet."),
    ("Orange", "adj.", "Loko voasary", "Couleur du fruit orange.", "Un sac de couleur orange.", "Sakosy loko voasary."),
    ("Pantalon", "n.m.", "Pataloha", "Vêtement couvrant les jambes.", "Ce pantalon est trop long.", "Lava loatra ity pataloha ity."),
    ("Chemise", "n.f.", "Chemise / Akanjo ambony", "Vêtement à boutons pour le haut du corps.", "Mets une chemise propre.", "Manoa chemise madio."),
    ("Robe", "n.f.", "Akanjo vavy / Robe", "Vêtement féminin d'une seule pièce.", "Sa robe est magnifique.", "Tena kanto ny robe-ny."),
    ("Jupe", "n.f.", "Chio / Jupe", "Vêtement féminin s'attachant à la taille.", "Elle porte une jupe plissée.", "Mano jupe izy."),
    ("Manteau", "n.m.", "Manteau / Akanjo mafana", "Vêtement chaud pour l'extérieur.", "Mets ton manteau, il fait froid.", "Manoa manteau, mangatsiaka ny andro."),
    ("Veste", "n.f.", "Veste", "Vêtement court boutonné sur le devant.", "Une veste de costume élégante.", "Veste eleganty."),
    ("Chaussures", "n.f.pl.", "Kiraro", "Accessoire pour chausser les pieds.", "Ces chaussures sont très confortables.", "Tena mahafinaritra ireto kiraro ireto."),
    ("Chaussettes", "n.f.pl.", "Bas / Chaussettes", "Vêtement de pied sous la chaussure.", "Portez des chaussettes en coton.", "Manoa chaussettes coton."),
    ("Chapeau", "n.m.", "Malo / Satroka", "Couvre-chef contre le soleil.", "Le satroka gass protège du soleil.", "Miantoka amin'ny masoandro ny satroka gass."),
    ("Ceinture", "n.f.", "Fehi-kibo", "Bande pour maintenir le pantalon.", "Serre ta ceinture.", "Fehezo ny fehi-kibo."),
    ("Sac", "n.m.", "Sakosy", "Accessoire pour porter des objets.", "Mon sac est lourd.", "Mavandy ny sakosy-ko."),
    ("Lunettes", "n.f.pl.", "Masoandro / Lunettes", "Accessoire de vue ou solaire.", "Il porte des lunettes de soleil.", "Mano lunettes masoandro izy."),
    ("Montre", "n.f.", "Famantaranandro", "Appareil porté au poignet indiquant l'heure.", "Ma montre indique midi.", "Asehon'ny famantaranandroko ny atoandro."),
    ("Bijou", "n.m.", "Firahakandro / Bijou", "Objet de parure précieux.", "Un beau bijou en or.", "Bijou volamena tsara."),
    ("T-shirt", "n.m.", "T-shirt", "Maillot de corps à manches courtes.", "Un T-shirt en coton blanc.", "T-shirt coton fotsy."),
    ("Costume", "n.m.", "Costume", "Ensemble veste et pantalon assortis.", "Il porte un costume pour la cérémonie.", "Mano costume amin'ny lanonana izy."),
    ("Gants", "n.m.pl.", "Gants / Fonon-tanana", "Accessoire protégeant les mains du froid.", "Des gants en cuir chaud.", "Gants cuirs mafana."),
    ("Parapluie", "n.m.", "Evolan-drains / Parapluie", "Accessoire pour se protéger de la pluie.", "N'oublie pas ton parapluie !", "Aza adino ny parapluie-nao !")
]
