items = [
    ("Cahier", "n.m.", "Kaye / Kahie", "Assemblage de feuilles pour écrire.", "Écris la leçon dans ton cahier.", "Soraty ao an-kahie ny lesona."),
    ("Stylo", "n.m.", "Stylo / Penina", "Outil servant à écrire avec de l'encre.", "Prête-moi ton stylo bleu.", "Ampindramo ahy ny stylo manganao."),
    ("Cours", "n.m.", "Lesona / Fampianarana", "Enseignement donné par un professeur.", "Le cours commence à huit heures.", "Manomboka amin'ny valo ora ny fampianarana."),
    ("Leçon", "n.f.", "Lesona", "Enseignement à apprendre.", "Révise ta leçon pour demain.", "Atsaharo ny lesonao ho ampitso."),
    ("Examen", "n.m.", "Fanadinana", "Épreuve d'évaluation des connaissances.", "L'examen aura lieu à la fin du mois.", "Atao amin'ny faran'ny volana ny fanadinana."),
    ("Musique", "n.f.", "Mozika", "Art de combiner les sons.", "J'écoute de la musique malgache.", "Mihaino mozika malagasy aho."),
    ("Danse", "n.f.", "Dihy", "Mouvement du corps en rythme.", "La danse traditionnelle est magnifique.", "Tena kanto ny dihy valimbahiny."),
    ("Histoire", "n.f.", "Tantara", "Récit des faits passés.", "L'histoire de Madagascar est riche.", "Manana tantara be i Madagasikara."),
    ("Art", "n.m.", "Kanto / Kanto-kanto", "Création d'œuvres esthétiques.", "L'artisanat est un art populaire.", "Kanto malaza ny fahaizana tanana."),
    ("Fête", "n.f.", "Fety", "Réunion joyeuse pour célébrer.", "Joyeuse fête de l'Indépendance !", "Joyeuse fety ny Fahaleovantena !"),
    ("Tradition", "n.f.", "Fomba gass / Fomba", "Coutume transmise de génération en génération.", "Respecter les traditions locales.", "Manaja ny fomba gass an-toerana."),
    ("Étudiant", "n.m.", "Mpianatra ambonin'ny ambaratonga", "Personne qui suit des études supérieures.", "L'étudiant prépare sa thèse.", "Manomana thesis ny mpianatra."),
    ("Élève", "n.m.", "Mpianatra", "Enfant qui va à l'école.", "L'élève écoute attentivement le maître.", "Mihaino tsara ny mpampianatra ny mpianatra."),
    ("Professeur", "n.m.", "Mpampianatra", "Enseignant dans un lycée ou université.", "Le professeur explique la règle.", "Manazava ny lalana ny mpampianatra."),
    ("Devoir", "n.m.", "Karakara / Devoir", "Travail donné aux élèves à faire à la maison.", "Fais tes devoirs avant de jouer.", "Atao ny devoir alohan'ny hilalaovana."),
    ("Note", "n.f.", "Noma / Naoty", "Appréciation chiffrée d'un travail.", "Il a obtenu une excellente note.", "Nahazo naoty tsara be izy."),
    ("Diplôme", "n.m.", "Diplaoma", "Titre attestant de réussites d'études.", "Elle a obtenu son diplôme universitaire.", "Nahazo diplaoma oniversite izy."),
    ("Classe", "n.f.", "Kilasy", "Groupe d'élèves de même niveau.", "La classe compte trente élèves.", "Manana mpianatra roa ambin'ny folo ny kilasy."),
    ("Bibliothèque", "n.f.", "Trano famakiam-boky", "Lieu où sont conservés les livres.", "Je lis au calme à la bibliothèque.", "Mamaky boky am-pimonina ao an-trano famakiam-boky aho."),
    ("Science", "n.f.", "Siansa", "Ensemble de connaissances rationnelles.", "La science fait progresser l'humanité.", "Mampiroso ny olombelona ny siansa."),
    ("Internet", "n.m.", "Aterineto / Internet", "Réseau informatique mondial.", "La connexion Internet est très rapide.", "Tena haingana ny Internet."),
    ("Écran", "n.m.", "Écran", "Surface d'affichage d'un ordinateur.", "L'écran affiche une image claire.", "Maneho sary madio ny écran."),
    ("Réseau", "n.m.", "Réseau", "Ensemble d'équipements interconnectés.", "Le réseau téléphonique fonctionne bien.", "Mandeha tsara ny réseau finday."),
    ("Photo", "n.f.", "Sary", "Image obtenue par appareil photographique.", "Prends une photo du paysage.", "Maka sary ny tanàna."),
    ("Vidéo", "n.f.", "Vidéo", "Enregistrement d'images animées.", "Regarde cette vidéo éducative.", "Jereo ity vidéo fampianarana ity."),
    ("Application", "n.f.", "Appli / Fampiharana", "Programme informatique sur téléphone.", "Téléchargez l'application sur votre mobile.", "Ampidiro ao amin'ny finday ny appli."),
    ("Site", "n.m.", "Tranonkala", "Ensemble de pages web sur Internet.", "Consultez notre site tranonkala.", "Jereo ny tranonkalanay."),
    ("Code", "n.m.", "Kôdy", "Système de signes ou instructions.", "Entrez votre code de sécurité.", "Ampidiro ny kôdy fiarovana."),
    ("Batterie", "n.f.", "Vato / Batterie", "Accumulateur d'énergie électrique.", "Recharge la batterie de ton téléphone.", "Ampidiro vato ny findainao."),
    ("Clavier", "n.m.", "Clavier / Kitendry", "Ensemble de touches pour taper du texte.", "Taper sur le clavier de l'ordinateur.", "Manoratra amin'ny clavier ordinatera.")
]
