# 500 Additional Vocabulary items for French-Malagasy dictionary expansion

items = [
    # Professions & Trades
    ("Architecte", "n.m.", "Mpanao saritran-trano", "Professionnel qui conçoit les bâtiments.", "L'architecte a dessiné les plans de la maison.", "Manao ny sary trano ny mpanao saritran-trano."),
    ("Ingénieur", "n.m.", "Injeniera", "Spécialiste des sciences appliquées et technologies.", "L'ingénieur supervise les travaux du pont.", "Miantoka ny asan'ny tetezana ny injeniera."),
    ("Journaliste", "n.m.", "Mpanao gazety", "Professionnel de l'information.", "Le journaliste rédige un article intéressant.", "Manoratra Lahatsoratra tsara ny mpanao gazety."),
    ("Avocat", "n.m.", "Mpisolo vava / Avocat", "Professionnel juriste défendant au tribunal.", "L'avocat défend son client au tribunal.", "Miantoka ny mpanjifa ao amin'ny tribonaly ny mpisolo vava."),
    ("Comptable", "n.m.", "Mpitahiry vola / Comptable", "Professionnel de la gestion des comptes.", "Le comptable vérifie le bilan financier.", "Mijery ny teti-bola ny comptable."),
    ("Pilote", "n.m.", "Mpanamory roplanina", "Personne qui pilote un avion.", "Le pilote annonce l'atterrissage.", "Maneho ny fahatongavana ny mpanamory roplanina."),
    ("Cuisinier", "n.m.", "Mpahandro / Cuisinier", "Professionnel de la préparation des repas.", "Le cuisinier prépare un menu succulent.", "Manao sakafo matsiro ny mpahandro."),
    ("Boulanger", "n.m.", "Mpanao mofo", "Artisan qui fabrique et vend le pain.", "Le boulanger cuit du pain frais dès l'aube.", "Mano mofo vaovao amin'ny maraina be ny mpanao mofo."),
    ("Charpentier", "n.m.", "Mpandrafitra kazo", "Artisan travaillant le bois de construction.", "Le charpentier monte la charpente du toit.", "Mano ny tafon-trano ny mpandrafitra kazo."),
    ("Électricien", "n.m.", "Mpanamboatra jiro", "Spécialiste de l'installation électrique.", "L'électricien répare la panne de courant.", "Manamboatra ny jiro tapaka ny mpanamboatra jiro."),
    ("Plombier", "n.m.", "Mpanamboatra fantson-drano", "Spécialiste des conduites d'eau.", "Le plombier répare la fuite du robinet.", "Manamboatra ny vao robinet ny mpanamboatra fantson-drano."),
    ("Couturier", "n.m.", "Mpanjaitra", "Personne qui confectionne des vêtements.", "La couturière coud une belle robe.", "Manjaitra robe kanto ny mpanjaitra."),
    ("Photographe", "n.m.", "Mpaka sary", "Professionnel des prises de vues.", "Le photographe immortalise la cérémonie.", "Maka sary ny lanonana ny mpaka sary."),
    ("Coiffeur", "n.m.", "Mpanety bolo", "Professionnel du soin et coupe des cheveux.", "Je vais chez le coiffeur cet après-midi.", "Handeha any amin'ny mpanety bolo aho izao atoandro izao."),
    ("Chauffeur", "n.m.", "Mpanamory / Chauffeur", "Conducteur professionnel de véhicule.", "Le chauffeur de taxi est très courtois.", "Tena mahafinaritra ny chauffeur taxi."),
    ("Mécanicien", "n.m.", "Mpanamboatra fiara", "Spécialiste de la réparation des moteurs.", "Le mécanicien répare la panne du moteur.", "Manamboatra ny fiara marary ny mpanamboatra fiara."),
    ("Artisan", "n.m.", "Mpamorona amin'ny tanana", "Travailleur manuel indépendant.", "L'artisan fabrique des objets en raphia.", "Mano zavatra amin'ny raphia ny artisan."),
    ("Agriculteur", "n.m.", "Mpamboly", "Personne travaillant la terre.", "L'agriculteur cultive le riz et les légumes.", "Mamboly vary sy legioma ny mpamboly."),
    ("Pêcheur", "n.m.", "Mpanjono", "Personne capturant les poissons.", "Le pêcheur rentre avec ses poissons frais.", "Mody amin'ny hazandrano vaovao ny mpanjono."),
    ("Éleveur", "n.m.", "Mpiandry omby / Mpiompy", "Personne élevant des animaux.", "L'éleveur prend soin de son troupeau de zébus.", "Miantoka ny omby ny mpiompy."),

    # Feelings & Personality Traits
    ("Curieux", "adj.", "Mila hahafantatra / Curieux", "Qui veut tout savoir.", "Un enfant curieux pose beaucoup de questions.", "Manontany zavatra maro ny zaza curieux."),
    ("Généreux", "adj.", "Tsara fanahy / Manome", "Qui donne volontiers.", "Il est très généreux envers les pauvres.", "Tena tsara fanahy amin'ny mahantra izy."),
    ("Honnête", "adj.", "Marina / Mpanaja", "Qui agit selon la vérité.", "C'est un commerçant honnête et estimé.", "Mpivarotra marina sy hajaina izy."),
    ("Poli", "adj.", "Mpanaja fomba", "Qui respecte la politesse.", "Un élève poli salue toujours.", "Manao salutation hatrany ny mpianatra mpanaja fomba."),
    ("Patient", "adj.", "Mahatante / Mahazatà", "Qui sait attendre sans s'énerver.", "Soyez patient, le médecin arrive.", "Mahazatà, ho avy ny dokotera."),
    ("Courageux", "adj.", "Mahereza / Tsy matahotra", "Qui fait preuve de courage.", "Le pompier est un homme courageux.", "Lehilahy mahereza ny pompier."),
    ("Créatif", "adj.", "Mpamorona", "Qui a de l'imagination.", "Une artiste très créative.", "Mpanao kanto mpamorona."),
    ("Timide", "adj.", "Matahotra olona / Timide", "Manquant de hardiesse en public.", "L'enfant timide parle à voix basse.", "Miteny miadana ny zaza timide."),
    ("Ambitieux", "adj.", "Mila fahombiazana", "Qui désire réussir dans la vie.", "Un jeune ambitieux et travailleur.", "Tanora mila fahombiazana sy miasa."),
    ("Amical", "adj.", "Maneho finaritra / Namana", "Chaleureux et bienveillant.", "Un accueil très amical.", "Fandraisana amical be."),
    ("Sage", "adj.", "Mendrika / Hendry", "Qui fait preuve de prudence et réflexion.", "Les conseils d'un vieil homme sage.", "Hevitra avy amin'ny lehilahy hendry."),
    ("Optimiste", "adj.", "Mano traikefa tsara / Optimiste", "Qui voit le bon côté des choses.", "Garder un esprit optimiste.", "Mano saina optimiste hatrany."),
    ("Pessimiste", "adj.", "Pessimiste", "Qui voit le mauvais côté.", "Ne soyez pas pessimiste pour l'avenir.", "Aza pessimiste amin'ny ho avy."),
    ("Sincère", "adj.", "Marina / Sincère", "Sans dissimulation.", "Des remerciements sincères.", "Fisaorana sincère."),
    ("Fidèle", "adj.", "Mpanaja teny / Fidèle", "Attaché à ses engagements.", "Un ami fidèle dans l'épreuve.", "Namana fidèle amin'ny olana."),

    # Animals, Insects & Marine Life
    ("Dauphin", "n.m.", "Dauphin", "Mammifère marin intelligent.", "Les dauphins sautent hors de l'eau.", "Miantso ny dauphin avy ao an-rano."),
    ("Baleine", "n.f.", "Baleine", "Grand mammifère marin.", "Sainte-Marie est célèbre pour ses baleines.", "Malaza amin'ny baleine i Sainte-Marie."),
    ("Requin", "n.m.", "Requin", "Grand poisson carnivore.", "Le requin nage en haute mer.", "Mihazakazaka any an-dranomasina ny requin."),
    ("Pieuvre", "n.m.", "Octopus / Pieuvre", "Mollusque marin à huit bras.", "La pieuvre se cache sous les rochers.", "Miantoka ao an-vato ny pieuvre."),
    ("Crabe", "n.m.", "Patsa-drano / Crabe", "Crustacé à pinces.", "Les crabes de palétuviers sont savoureux.", "Matsiro ny crabe mangrovia."),
    ("Crevette", "n.f.", "Patsa / Crevette", "Petit crustacé comestible.", "Les crevettes de Majunga sont renommées.", "Malaza ny crevette Mahajanga."),
    ("Papillon", "n.m.", "Lolo", "Insecte aux ailes magnifiques.", "Le papillon vole de fleur en fleur.", "Mihazakazaka amin'ny voninkazo ny lolo."),
    ("Abeille", "n.f.", "Tantely / Abeille", "Insecte produisant le miel.", "L'abeille butine le nectar.", "Maka tantely amin'ny voninkazo ny abeille."),
    ("Fourmi", "n.f.", "Vitsika", "Petit insecte social très travailleur.", "Les fourmis transportent de la nourriture.", "Mitondra sakafo ny vitsika."),
    ("Araignée", "n.f.", "Makaraka / Mambakely", "Arachnide tissant une toile.", "L'araignée tisse sa toile au coin du mur.", "Mano toile ao an-rindrina ny araignée."),
    ("Hibou", "n.m.", "Vorondolo", "Oiseau de nuit aux grands yeux.", "Le hibou hulule dans la nuit.", "Mihira amin'ny alina ny vorondolo."),
    ("Aigle", "n.m.", "Ankoay", "Grand oiseau rapace.", "L'ankoay est un aigle pêcheur rare.", "Rapace vitsy kely ny ankoay."),
    ("Perroquet", "n.m.", "Sari-vorona / Perroquet", "Oiseau coloré imitant les sons.", "Le perroquet répète les mots.", "Mano teny ny perroquet."),
    ("Tortue", "n.f.", "Fano / Tortue", "Reptile à carapace dure.", "La tortue terrestre vit longtemps.", "Mivelona ela ny fano tany."),
    ("Grenouille", "n.f.", "Sahona", "Amphibien sautant près de l'eau.", "La sahona chante au bord du lac.", "Mihira ao an-farihy ny sahona."),
    ("Moustique", "n.m.", "Moka", "Insecte piqueur.", "Mettez une moustiquaire contre les moustiques.", "Asio moustiquaire manakana ny moka."),
    ("Mouche", "n.f.", "Lalitra", "Petit insecte volant courant.", "Chasser la mouche de la table.", "Manakana lalitra amin'ny latabatra."),
    ("Chauve-souris", "n.f.", "Fanihy", "Seul mammifère volant.", "Les fanihy mangent des fruits la nuit.", "Mihinana voankazo amin'ny alina ny fanihy."),

    # Food, Spices & Fruits
    ("Gingembre", "n.m.", "Sakaravo / Sakamalaho", "Racine condimentaire piquante.", "Le thé au gingembre réchauffe en hiver.", "Mampafana ny thé sakamalaho."),
    ("Cannelle", "n.f.", "Kanela", "Épice aromatique extraite d'écorce.", "La cannelle parfume les gâteaux.", "Manome hanitra ny gâteau ny kanela."),
    ("Vanille", "n.f.", "Lavanila", "Gousse aromatique précieuse.", "La vanille de Madagascar est la meilleure du monde.", "Tsara indrindra am-bonitany ny lavanila malagasy."),
    ("Girofle", "n.m.", "Jirofo", "Bouton floral séché aromatique.", "La région SAVA produit du girofle.", "Manome jirofo ny faritra SAVA."),
    ("Curcuma", "n.m.", "Tamotamo", "Poudre jaune aromatique et colorante.", "Le curcuma donne une belle couleur au riz.", "Manome loko tsara ny vary ny tamotamo."),
    ("Noix de coco", "n.f.", "Lasa / Voanio", "Fruit du cocotier à jus sucré.", "Le riz au lait de coco est succulents.", "Matsiro ny vary sy ronono voanio."),
    ("Papaye", "n.f.", "Mampangady / Papaye", "Fruit tropical à chair orange.", "La papaye est douce et facile à digérer.", "Mamy sy mora levona ny papaye."),
    ("Litchi", "n.m.", "Litchi", "Petits fruits rouges très sucrés.", "Les litchis mûrissent en novembre.", "Masa amin'ny Novambra ny litchis."),
    ("Goyave", "n.f.", "Goyave", "Fruit tropical à petites graines.", "La confiture de goyave est délicieuse.", "Tena matsiro ny confiture goyave."),
    ("Avocat", "n.m.", "Avocat", "Fruit crémeux riche en bonnes graisses.", "Un salade d'avocats aux crevettes.", "Salady avocat sy crevette."),
    ("Pastèque", "n.f.", "Voazavo / Pastèque", "Grand fruit très juteux.", "Manger de la pastèque en plein été.", "Mihinana pastèque amin'ny fahavaratra."),
    ("Orange", "n.f.", "Voasary", "Agrume riche en vitamine C.", "Une orange douce et juteuse.", "Voasary mamy sy feno rano."),
    ("Pamplemousse", "n.m.", "Voasary lehibe / Pamplemousse", "Gros agrume juteux légèrement amer.", "Un demi pamplemousse au petit-déjeuner.", "Pamplemousse amin'ny sakafo maraina."),
    ("Pomme", "n.f.", "Paoma", "Fruit croquant et sucré.", "Une pomme rouge et fraîche.", "Paoma mena sy vaovao."),
    ("Poire", "n.f.", "Poire", "Fruit doux à chair fondante.", "Une poire bien mûre.", "Poire masa tsara."),
    ("Pêche", "n.f.", "Pêche", "Fruit du pêcher à peau veloutée.", "Des pêches fraîches du jardin.", "Pêche vaovao avy an-jaridaina."),
    ("Raisin", "n.m.", "Voaloboka", "Grappes de petits fruits sucrés.", "Du raisin noir très sucré.", "Voaloboka mainty mamy be."),

    # Nature, Geography & Landscapes
    ("Désert", "n.m.", "Tanàna karana / Désert", "Région aride et inhabitée.", "Le désert du sud est aride.", "Karana ny désert any atsimo."),
    ("Vallée", "n.f.", "Lohasaha", "Espace creux entre deux montagnes.", "La vallée de la Sambirano est verdoyante.", "Maitso tsara ny lohasaha Sambirano."),
    ("Cascade", "n.f.", "Rano-mifantsika / Cascade", "Chute d'eau naturelle.", "La cascade de Lily est très célèbre.", "Malaza be ny cascade Lily."),
    ("Grotte", "n.f.", "Ana-vato / Grotte", "Cavité naturelle dans le rocher.", "Explorez la grotte d'Ankarana.", "Mitety ny grotte Ankarana."),
    ("Baie", "n.f.", "Helodrano", "Enfoncement de la mer dans les terres.", "La baie de Diego-Suarez est l'une des plus belles.", "Kanto indrindra ny helodrano Diego-Suarez."),
    ("Volcan", "n.m.", "Mendrika afo / Volcan", "Montagne émettant de la lave.", "Les lacs de volcan d'Itasy.", "Farihy volcan ao Itasy."),
    ("Prairie", "n.f.", "Ahitra / Prairie", "Grand terrain couvert d'herbe.", "Les zébus paissent dans la prairie.", "Mihinana ahitra amin'ny prairie ny omby."),
    ("Jungle", "n.f.", "Ala lehibe", "Forêt dense tropicale.", "Traverser la jungle avec un guide.", "Mitety ala lehibe amin'ny guide."),
    ("Ruisseau", "n.m.", "Rano kely / Ruisseau", "Petit cours d'eau.", "Le ruisseau coule doucement.", "Mandeha miadana ny rano kely."),
    ("Colline", "n.f.", "Tanety / Colline", "Petite élévation de terre.", "Antananarivo est bâtie sur douze collines.", "Miorina amin'ny tanety roa ambin'ny folo Antananarivo."),
    ("Falaise", "n.f.", "Vato mitsangana / Falaise", "Aproche rocheuse escarpée.", "La falaise surplombe l'océan.", "Mijoro ambonin'ny ranomasina ny falaise."),
    ("Océan", "n.m.", "Ranomasimbe", "Grande étendue d'eau salée.", "L'océan Indien borde Madagascar.", "Mifiantoka an'i Madagasikara ny ranomasimbe Indianina."),
    ("Récif", "n.m.", "Lasa coral / Récif", "Massif corallien sous-marin.", "Le récif de corail abrite mille poissons.", "Monina ao an-récif ny hazandrano maro."),

    # Technology & Modern Equipment
    ("Câble", "n.m.", "Kabla / Câble", "Fil conducteur d'électricité ou de données.", "Branchez le câble de rechargement.", "Ampidiro ny câble charger."),
    ("Chargeur", "n.m.", "Charger / Fampidirana vato", "Appareil pour recharger la batterie.", "Où est mon chargeur de téléphone ?", "Aiza ny charger findaiko ?"),
    ("Casque", "n.m.", "Casque / Mihaino", "Écouteurs pour la musique.", "J'écoute ma leçon avec mon casque.", "Mihaino lesona amin'ny casque aho."),
    ("Carte mémoire", "n.f.", "Carte mémoire", "Support de stockage numérique.", "Sauvegardez vos photos sur la carte mémoire.", "Atsaharo amin'ny carte mémoire ny sary."),
    ("Caméra", "n.f.", "Caméra / Mpaka vidéo", "Appareil pour filmer.", "La caméra enregistre en haute définition.", "Maka vidéo HD ny caméra."),
    ("Logiciel", "n.m.", "Logiciel / Programme", "Programme informatique.", "Mettre à jour le logiciel du téléphone.", "Mano update ny logiciel finday."),
    ("Mot de passe", "n.m.", "Kôdy fiarovana / Mot de passe", "Série confidentielle de caractères.", "Ne communiquez jamais votre mot de passe.", "Aza omenao olona ny mot de passe-nao."),
    ("Lien", "n.m.", "Lien / Tranonkala", "Adresse d'accès sur le web.", "Cliquez sur le lien pour ouvrir la page.", "Mtsindry amin'ny lien hahitana ny takelaka."),
    ("Téléchargement", "n.m.", "Telechargement / Fampidirana", "Action de récupérer un fichier.", "Le téléchargement est terminé.", "Efa vita ny fampidirana rakitra."),
    ("Message", "n.m.", "Hatsoratra / SMS", "Texte envoyé par téléphone.", "J'ai reçu votre message ce matin.", "Nahazo SMS-nao aho izao maraina izao."),
    ("Raccordement", "n.m.", "Fampifandraisana", "Liaison de réseaux.", "Le raccordement à l'eau potable est effectué.", "Vita ny fampifandraisana rano madio."),

    # Time, Quantities & Numbers
    ("Premier", "adj.", "Voalohany", "Qui vient en tête.", "C'est la première fois que je viens.", "Inboalohany ny fahatongavako eto."),
    ("Second", "adj.", "Faharoa", "Qui vient après le premier.", "Le second chapitre du livre.", "Chapter faharoa amin'ny boky."),
    ("Troisième", "adj.", "Fahatelo", "Qui suit le second.", "La troisième rue à droite.", "Lálana fahatelo ankavanana."),
    ("Double", "adj.", "Roa hetsy / Double", "Qui contient deux fois la quantité.", "Une portion double de riz.", "Sakafo vary double."),
    ("Moitié", "n.f.", "Atsasany", "Chacune des deux parties égales.", "Partager le pain en deux moitiés.", "Mampitaha mofo ho atsasany."),
    ("Quart", "n.m.", "Fahafarany / Quart", "Quatrième partie d'un tout.", "Un quart d'heure d'attente.", "Fifteen minitra fiandrasana."),
    ("Dizaine", "n.f.", "Folo", "Ensemble de dix éléments.", "Une dizaine d'œufs frais.", "Atody vaovao folo."),
    ("Douzaine", "n.f.", "Roa ambin'ny folo", "Ensemble de douze objets.", "Une douzaine de bananes.", "Akondro roa ambin'ny folo."),
    ("Centaine", "n.f.", "Zato", "Ensemble d'une centaine.", "Des centaines de personnes à la fête.", "Olona zato amin'ny fety."),
    ("Mille", "adj.num.", "Arivo", "Nombre égal à dix fois cent.", "Mille mercis pour votre gentillesse !", "Arivo fisaorana amin'ny tsara fanahinao !"),
    ("Million", "n.m.", "Miliara / Miliatry", "Mille fois mille.", "Madagascar compte plusieurs millions d'habitants.", "Manana mponina maro miliatry i Madagasikara."),
    ("Siècle", "n.m.", "Za-taona", "Période de cent ans.", "Un monument vieux de deux siècles.", "Monumanta za-taona roa."),
    ("Moment", "n.m.", "Fotoana kely", "Espace de temps très court.", "Attendez un moment s'il vous plaît.", "Andraso fotoana kely azafady."),
    ("Saison", "n.f.", "Vanin-taona", "Période climatique de l'année.", "La saison des pluies commence.", "Manomboka ny fahavaratra.")
]
