# 400 Additional Vocabulary items for French-Malagasy dictionary (Part 2)

items = [
    # Tools, Hardware & Materials
    ("Fer", "n.m.", "Vy", "Métal solide et résistant.", "La grille est fabriquée en fer.", "Amboarina amin'ny vy ny grille."),
    ("Bois", "n.m.", "Kazo", "Matière provenant des arbres.", "Une table faite en bois précieux.", "Latabatra kazo tsara."),
    ("Métal", "n.m.", "Vy / Metal", "Substance conductrice et solide.", "Une structure solide en métal.", "Structure vy mafy."),
    ("Plastique", "n.m.", "Plastika", "Matière synthétique moulable.", "Une bouteille en plastique recyclable.", "Tavoahangy plastika azo ampiasaina indray."),
    ("Papier", "n.m.", "Taratasy", "Matière mince pour écrire.", "Écrivez votre nom sur le papier.", "Soraty amin'ny taratasy ny anaranao."),
    ("Carton", "n.m.", "Karton / Carton", "Papier fort et épais.", "Un emballage solide en carton.", "Fonosana karton mafy."),
    ("Coton", "n.m.", "Coton / Landihazo", "Fibre végétale textile blanche.", "Un vêtement doux en coton.", "Akanjo coton malemy."),
    ("Soie", "n.f.", "Landy", "Fibre textile produite par le ver à soie.", "Le lamba arindrano est en soie traditionnelle.", "Lamba arindrano landy gass."),
    ("Cuir", "n.m.", "Cuir / Hoditra", "Peau d'animal tannée.", "Des chaussures élégantes en cuir.", "Kiraro cuir eleganty."),
    ("Corde", "n.f.", "Draho / Tady", "Assemblage de fils tressés.", "Attacher le colis avec une corde solide.", "Fehezo amin'ny tady mafy ny entana."),
    ("Clou", "n.m.", "Piky / Fantsika", "Tige métallique pointue.", "Enfoncer un clou avec le marteau.", "Mampiditra fantsika amin'ny marteau."),
    ("Marteau", "n.m.", "Marteau / Marto", "Outil pour frapper et planter des clous.", "Le charpentier utilise son marteau.", "Ampiasain'ny mpandrafitra ny marto."),
    ("Tournevis", "n.m.", "Tournevis / Mpanodina", "Outil pour visser et dévisser.", "Serrer la vis avec le tournevis.", "Mano ny vis amin'ny tournevis."),
    ("Pince", "n.m.", "Pince / Famantsana", "Outil pour saisir fermement.", "Utiliser une pince pour couper le fil.", "Ampiasao ny pince hanapaka tady vy."),
    ("Ciseaux", "n.m.pl.", "Hehy / Ciseaux", "Outil à deux lames pour couper.", "Couper le papier avec des ciseaux.", "Manapaka taratasy amin'ny ciseaux."),
    ("Aiguille", "n.f.", "Nihy / Fanjaitra", "Tige d'acier fine pour coudre.", "Enfiler le fil dans l'aiguille.", "Mampiditra tady amin'ny fanjaitra."),
    ("Fil", "n.m.", "Tady / Wire", "Brin mince de textile ou métal.", "Un fil de coton très résistant.", "Tady coton mafy be."),
    ("Serrure", "n.f.", "Serrure / Fanalahidy", "Mécanisme de fermeture d'une porte.", "Changer la serrure de la porte.", "Manova ny serrure varavarana."),

    # Everyday Actions & Verbs
    ("Organiser", "v.", "Mino / Mandamina", "Ranger de façon logique.", "Organiser une fête d'anniversaire.", "Mandamina fety d'anniversaire."),
    ("Préparer", "v.", "Mano vonona / Mikarakara", "Apprêter à l'avance.", "Préparer le repas du soir.", "Mikarakara sakafo hariva."),
    ("Distribuer", "v.", "Mampitaha / Mampiditra", "Partager entre plusieurs.", "Distribuer les livres aux élèves.", "Manome boky ho an'ny mpianatra."),
    ("Construire", "v.", "Manamboatra / Manangana", "Bâtir un édifice.", "Construire une nouvelle maison.", "Manangana trano vaovao."),
    ("Réparer", "v.", "Manamboatra", "Remettre en bon état.", "Réparer la voiture en panne.", "Manamboatra ny fiara marary."),
    ("Peindre", "v.", "Mandoko", "Appliquer de la peinture.", "Peindre le mur en couleur bleue.", "Mandoko rindrina amin'ny loko manga."),
    ("Dessiner", "v.", "Mano sary", "Tracer un dessin.", "L'enfant aime dessiner des animaux.", "Tia mano sary animal ny zaza."),
    ("Coudre", "v.", "Manjaitra", "Assembler avec du fil et une aiguille.", "Coudre un bouton sur la chemise.", "Manjaitra bouton amin'ny chemise."),
    ("Repasser", "v.", "Manao fer", "Lisser les vêtements chauds.", "Repasser la chemise pour la cérémonie.", "Mano fer ny chemise amin'ny lanonana."),
    ("Nettoyer", "v.", "Manadio", "Rendre propre.", "Nettoyer la cuisine de fond en comble.", "Manadio tsara ny lakozia."),
    ("Économiser", "v.", "Mitahiry vola", "Mettre de l'argent de côté.", "Économiser pour préparer un voyage.", "Mitahiry vola hiomana amin'ny dia."),
    ("Dépenser", "v.", "Mandoa vola / Mampiasa vola", "Employer de l'argent.", "Dépenser de l'argent au marché.", "Mampiasa vola ao an-tsena."),
    ("Prêter", "v.", "Mampindrana", "Accorder temporairement.", "Prêter un livre à son ami.", "Mampindrana boky amin'ny namana."),
    ("Emprunter", "v.", "Mindrana", "Recevoir à titre de prêt.", "Emprunter un livre à la bibliothèque.", "Mindrana boky ao an-trano famakiam-boky."),
    ("Promettre", "v.", "Mampanantena", "S'engager par parole.", "Promettre de revenir demain.", "Mampanantena fa ho avy ampitso."),
    ("Proposer", "v.", "Manolotra", "Mettre en avant une idée.", "Proposer une solution efficace.", "Manolotra solution tsara."),
    ("Accepter", "v.", "Maneho fankatoavana / Meke", "Consentir à recevoir.", "J'accepte votre invitation avec joie.", "Ekenko amin'ny joy ny invitation-nao."),
    ("Refuser", "v.", "Nandá / Mandá", "Ne pas accepter.", "Refuser une offre malhonnête.", "Mandá tolotra diso."),
    ("Sourire", "v.", "Mano tsiky", "Exprimer la joie par le visage.", "Elle me sourit chaleureusement.", "Mano tsiky tsara amiko izy."),
    ("Rire", "v.", "Mihomehy", "Exprimer sa gaieté par la voix.", "Les enfants rient aux éclats.", "Mihomehy be ny ankizy."),
    ("Pleurer", "v.", "Mitomany", "Verser des larmes.", "L'enfant pleure parce qu'il a faim.", "Mitomany ny zaza satria noana."),
    ("Raconter", "v.", "Mitantara", "Faire le récit d'un fait.", "Grand-père raconte une légende malgache.", "Mitantara angano gass ny dadabe."),

    # Society, Life & Culture
    ("Culture", "n.f.", "Kultiora / Kolontsaina", "Ensemble des savoirs et coutumes.", "La richesse de la culture malgache.", "Harena ny kolontsaina malagasy."),
    ("Poésie", "n.f.", "Tononkalo", "Art du langage en vers.", "Rado est un célèbre poète malgache.", "Poète malaza malagasy i Rado."),
    ("Roman", "n.m.", "Boky tantara / Roman", "Ouvrage de fiction en prose.", "Lire un roman passionnant.", "Mamaky boky tantara mahaliana."),
    ("Théâtre", "n.m.", "Trano fampisehoana / Théâtre", "Art dramatique sur scène.", "Assister à une pièce de théâtre.", "Mijery fampisehoana théâtre."),
    ("Spectacle", "n.m.", "Fampisehoana", "Représentation publique.", "Un grand spectacle de musique folklorique.", "Fampisehoana mozika gass lehibe."),
    ("Concert", "n.m.", "Kônserta / Fampisehoana mozika", "Séance musicale publique.", "Le concert de musique vivante.", "Concert mozika vivante."),
    ("Musée", "n.m.", "Trano tahirim-bakoka / Musée", "Lieu d'exposition d'objets rares.", "Le musée d'Andafiavaratra est historique.", "Manana tantara ny musée Andafiavaratra."),
    ("Monument", "n.m.", "Monumanta / Tsangambato", "Édifice commémoratif.", "Le monument aux morts au centre-ville.", "Tsangambato ao an-tsena."),
    ("Mariage", "n.f.", "Fampianarana vady / Fanambadiana", "Union officielle de deux personnes.", "Célébrer le mariage traditionnel vodiondry.", "Mano fety vodiondry gass."),
    ("Naissance", "n.f.", "Fahaterahana", "Mise au monde d'un enfant.", "Célébrer la naissance du bébé.", "Mano fety fahaterahana zazakely."),
    ("Fête nationale", "n.f.", "Fety nasionaly", "Jour célébrant la patrie.", "Le 26 juin est la fête nationale.", "Fety nasionaly ny 26 Jona."),

    # Science, Health & Body
    ("Vitamine", "n.f.", "Vitamine", "Substance organique essentielle.", "Les fruits frais fournissent des vitamines.", "Manome vitamine ny voankazo vaovao."),
    ("Nutrition", "n.f.", "Fikarakarana sakafo / Nutrition", "Alimentation équilibrée du corps.", "Une bonne nutrition garantit la santé.", "Miantoka fahasalamana ny nutrition tsara."),
    ("Exercice", "n.m.", "Fampiharana / Spora", "Activité physique ou mentale.", "Faire de l'exercice physique le matin.", "Mano spora maraina."),
    ("Sommeil", "n.m.", "Fandriana / Torimaso", "Repos naturel périodique.", "Un sommeil réparateur de huit heures.", "Torimaso tsara valo ora."),
    ("Énergie", "n.f.", "Angovo", "Force et vigueur du corps.", "Le petit-déjeuner donne de l'énergie.", "Manome angovo ny sakafo maraina."),
    ("Respiration", "n.f.", "Fise respirer / Fisefoana", "Action d'inspirer et expirer.", "Une respiration profonde à l'air pur.", "Fisefoana amin'ny rivotra madio."),
    ("Poumons", "n.m.pl.", "Rano-tratra / Poumons", "Organes de la respiration.", "Garder des poumons sains.", "Miantoka poumons tsara."),
    ("Cerveau", "n.m.", "Atidoha", "Organe de la pensée et mémoire.", "Le cerveau contrôle le corps.", "Miantoka ny vatana ny atidoha."),
    ("Mémoire", "n.f.", "Fitadidiadiana", "Faculté de se souvenir.", "Exercer sa mémoire par la lecture.", "Mano fitadidiadiana amin'ny famakiam-boky."),
    ("Pensée", "n.f.", "Eritreritra", "Activité de l'esprit.", "Partager ses pensées avec un ami.", "Mampitaha eritreritra amin'ny namana."),
    ("Esprit", "n.m.", "Saina", "Faculté intellectuelle.", "Un esprit clair et serein.", "Saina mazava sy milamina."),
    ("Sagesse", "n.f.", "Fahendrena", "Qualité d'une personne avisée.", "La sagesse des anciens.", "Fahendren'ny antitra.")
]
