items = [
    ("Pain", "n.m.", "Mofo", "Aliment à base de farine cuite.", "J'achète du pain frais le matin.", "Mividy mofo vaovao aho maraina."),
    ("Viande", "n.f.", "Hena", "Chair des animaux consommée comme aliment.", "Nous mangeons de la viande de zébu.", "Mihinana hena omby izahay."),
    ("Poisson", "n.m.", "Lazan-drano / Hazandrano", "Animal aquatique comestible.", "Le poisson est très frais.", "Tena vaovao ny hazandrano."),
    ("Poulet", "n.m.", "Akoho", "Volaille élevée pour sa chair.", "Le poulet rôti est délicieux.", "Tena matsiro ny akoho mendrika."),
    ("Lait", "n.f.", "Ronono", "Liquide blanc produit par les mammifères.", "Je bois du lait chaud au petit-déjeuner.", "Misotro ronono mafana aho amin'ny sakafo maraina."),
    ("Café", "n.m.", "Kafe", "Boisson préparée avec des graines torréfiées.", "Voulez-vous une tasse de café ?", "Mila tasse kafe ve ianao ?"),
    ("Thé", "n.m.", "Thé", "Boisson infusée à partir de feuilles de théier.", "Le thé vert est bon pour la santé.", "Tsara ho an'ny fahasalamana ny thé vert."),
    ("Sucre", "n.m.", "Sira-mamy / Siramamy", "Substance douce utilisée pour adoucir.", "Mets un peu de sucre dans mon café.", "Asio siramamy kely ny kafeko."),
    ("Sel", "n.m.", "Sira", "Condiment minéral blanc au goût salé.", "N'oublie pas d'ajouter du sel.", "Aza adino ny manampy sira."),
    ("Fruit", "n.m.", "Voankazo", "Produit comestible des végétaux.", "Les fruits frais sont pleins de vitamines.", "Feno vitamines ny voankazo vaovao."),
    ("Légume", "n.m.", "Anana / Legioma", "Plante potagère consommée aux repas.", "Les légumes sont bons pour le corps.", "Tsara ho an'ny vatana ny legioma."),
    ("Banane", "n.f.", "Akondro", "Fruit allongé à peau jaune.", "La banane est très sucrée.", "Tena mamy ny akondro."),
    ("Mangue", "n.f.", "Manga", "Fruit tropical charnu.", "Les mangues sont mûres en décembre.", "Masa amin'ny Desambra ny manga."),
    ("Ananas", "n.m.", "Mananas", "Fruit tropical à chair jaune sucrée.", "L'ananas est juteux et rafraîchissant.", "Manana rano sy mampangatsiatsiaka ny mananas."),
    ("Citron", "n.m.", "Sitiro / Voasarimakirana", "Agrume jaune au goût acide.", "Le jus de citron est riche en vitamine C.", "Riche amin'ny vitamine C ny ranom-boasarimakirana."),
    ("Œuf", "n.m.", "Atody", "Produit ponte par les oiseaux.", "Je mange un œuf au plat.", "Mihinana atody endasina aho."),
    ("Beurre", "n.m.", "Beurre / Dibera", "Matière grasse issue du lait.", "Mets du beurre sur le pain.", "Asio dibera amin'ny mofo."),
    ("Huile", "n.f.", "Menaka", "Matière grasse liquide pour la cuisson.", "Fais chauffer l'huile dans la poêle.", "Mano mafana menaka ao an-poêle."),
    ("Soupe", "n.f.", "Sabao / Sopa", "Potage liquide servi chaud.", "La soupe de légumes réchauffe en hiver.", "Mampafana amin'ny ririnina ny sopa legioma."),
    ("Jus", "n.m.", "Rano voankazo", "Liquide extrait des fruits.", "Un verre de jus d'orange s'il vous plaît.", "Vera ranom-boasary azafady."),
    ("Manioc", "n.m.", "Mahogo / Mangahazo", "Racine tubéreuse consommée cuite.", "Le manioc est un aliment de base.", "Sakafo fototra ny mangahazo."),
    ("Patate", "n.f.", "Voma / Vomanga", "Tubercule comestible doux.", "Les patates douces sont très bonnes.", "Tena tsara ny vomanga mamy."),
    ("Maïs", "n.m.", "Katsaka", "Céréale à épis et grains jaunes.", "Le maïs grillé est vendu au marché.", "Amidy ao an-tsena ny katsaka mendrika."),
    ("Tomate", "n.f.", "Tamotamo / Voatabia", "Fruit rouge utilisé comme légume.", "Prépare une salade de tomates.", "Karakarao ny salady voatabia."),
    ("Oignon", "n.m.", "Tongolo be", "Bulbe au goût fort pour cuisiner.", "Coupe l'oignon en petits morceaux.", "Tetho ho madinika ny tongolo be."),
    ("Ail", "n.m.", "Tongolo gass", "Bulbe condimentaire très odorant.", "L'ail donne du goût au plat.", "Manome tsiro ny sakafo ny tongolo gass."),
    ("Carotte", "n.f.", "Karoty", "Racine orange comestible.", "Râpe les carottes pour l'entrée.", "Rapoy ny karoty ho an'ny sakafo sora."),
    ("Haricot", "n.m.", "Lovy / Tsaramaso", "Légumineuse riche en protéines.", "Le riz avec du tsaramaso est délicieux.", "Tena matsiro ny vary sy tsaramaso."),
    ("Salade", "n.f.", "Salady", "Plat de légumes crus assaisonnés.", "Voulez-vous un peu de salade ?", "Mila salady kely ve ianao ?"),
    ("Fromage", "n.m.", "Fromage", "Produit laitier fermenté.", "Le fromage français est renommé.", "Malaza ny fromage frantsay."),
    ("Gâteau", "n.m.", "Gâteau", "Pâtisserie sucrée cuite au four.", "C'est mon gâteau d'anniversaire.", "Gâteau d'anniversaire-ko ity."),
    ("Chocolat", "n.m.", "Sokola", "Confiserie à base de cacao.", "Les enfants aiment le chocolat au lait.", "Tia sokola ronono ny ankizy."),
    ("Miel", "n.m.", "Tantely", "Substance sucrée produite par les abeilles.", "Le miel sauvage est naturel.", "Loharano ny tantely gass."),
    ("Poivre", "n.m.", "Manga / Dipoavatra", "Épice piquante pour assaisonner.", "Le poivre vert de Madagascar est célèbre.", "Malaza ny dipoavatra maitso avy any Madagasikara."),
    ("Farine", "n.f.", "Koba / Koba mofo", "Poudre issue de la mouture des céréales.", "Il faut de la farine pour faire le gâteau.", "Mila koba mofo hanao gâteau."),
    ("Rôti", "n.m.", "Mendrika / Rôti", "Viande cuite au four ou à la broche.", "Le rôti de porc est prêt.", "Vonona ny rôti kisoa."),
    ("Sauce", "n.f.", "Loka / Saosy", "Préparation liquide servant d'accompagnement.", "Versez la sauce sur le riz.", "Atsaharo amin'ny vary ny saosy."),
    ("Repas", "n.m.", "Sakafo", "Nourriture prise à des heures déterminées.", "Le repas est servi à midi.", "Atsaharo amin'ny atoandro ny sakafo."),
    ("Petit-déjeuner", "n.m.", "Sakafo maraina", "Premier repas de la journée.", "Je prends mon petit-déjeuner à sept heures.", "Mihinana sakafo maraina amin'ny fitoutoana aho."),
    ("Déjeuner", "n.m.", "Sakafo atoandro", "Repas du milieu de la journée.", "Le déjeuner est prêt.", "Vonona ny sakafo atoandro."),
    ("Dîner", "n.m.", "Sakafo hariva", "Repas du soir.", "Nous dînons en famille.", "Mihiraka misakafo hariva am-fianakaviana izahay.")
]
