items = [
    ("Aujourd'hui", "adv.", "Androany", "Le jour présent.", "Aujourd'hui, il fait beau.", "Tsara ny andro androany."),
    ("Demain", "adv.", "Ampitso", "Le jour qui suit aujourd'hui.", "Nous partirons demain matin.", "Hiala ampitso maraina isika."),
    ("Hier", "adv.", "Omaly", "Le jour précédant aujourd'hui.", "Hier soir, nous avons dîné ensemble.", "Omaly hariva, niaraka nisakafo izahay."),
    ("Maintenant", "adv.", "Izao / Ankehitriny", "Au moment présent.", "Venez ici maintenant.", "Avia eto izao."),
    ("Toujours", "adv.", "Hatrany / Mandrakariva", "En tout temps ou continuellement.", "Il est toujours à l'heure.", "Maha-fanaovana fotoana hatrany izy."),
    ("Jamais", "adv.", "Tsy mihitsy", "En aucun temps.", "Je n'ai jamais vu ce film.", "Tsy mbola nahita io film io mihitsy aho."),
    ("Souvent", "adv.", "Matetika", "Fréquemment.", "Nous allons souvent au marché.", "Mandeha matetika any an-tsena izahay."),
    ("Parfois", "adv.", "Manampy izany / Misy fotoana", "De temps en temps.", "Parfois, il pleut l'après-midi.", "Misy fotoana avy ny rainay atoandro."),
    ("Ici", "adv.", "Eto / Eto an-toerana", "Dans ce lieu.", "Asseyez-vous ici.", "Mhipetraha eto."),
    ("Là", "adv.", "Eo / Any", "Dans ce lieu déterminé.", "Attendez-moi là.", "Andraso ahy eo."),
    ("Partout", "adv.", "Na aiza na aiza / Tontolo", "En tout lieu.", "Les fleurs éclosent partout.", "Mamelana na aiza na aiza ny voninkazo."),
    ("Très", "adv.", "Tena / Be", "En haute quantité ou degré.", "C'est très bon.", "Tena matsiro izany."),
    ("Beaucoup", "adv.", "Betsaka", "En grande quantité.", "Merci beaucoup pour l'aide.", "Misaotra betsaka amin'ny fanampiana."),
    ("Peu", "adv.", "Kely", "En faible quantité.", "Un peu de sucre s'il vous plaît.", "Siramamy kely azafady."),
    ("Plus", "adv.", "Kokoa / Amby", "En plus grande quantité.", "Parlez plus lentement.", "Mitenena miadana kokoa."),
    ("Moins", "adv.", "Kokoa kely", "En moindre quantité.", "C'est moins cher.", "Mora kokoa izany."),
    ("Vite", "adv.", "Haingana", "À grande vitesse.", "Venez vite !", "Avia haingana !"),
    ("Lentement", "adv.", "Miadana", "À faible vitesse.", "Le vieil homme marche lentement.", "Mandeha miadana ny lehilahy antitra."),
    ("Avec", "prép.", "Miaraka amin'i / Amin'ny", "En compagnie de.", "Je viens avec mon ami.", "Avy miaraka amin'ny namako aho."),
    ("Sans", "prép.", "Tsy misy", "En l'absence de.", "Un café sans sucre.", "Kafe tsy misy siramamy."),
    ("Dans", "prép.", "Ao an- / Ao amin'ny", "À l'intérieur de.", "Le livre est dans le sac.", "Ao an-tsakosy ny boky."),
    ("Sur", "prép.", "Eo amin'ny / Ambonin'ny", "Au-dessus en touchant.", "La pomme est sur la table.", "Eo amin'ny latabatra ny paoma."),
    ("Sous", "prép.", "Aboan'ny / An-danin'ny", "Au-dessous de.", "Le chat est sous la chaise.", "Ao an-danin'ny seza ny saka."),
    ("Devant", "prép.", "An-front'ny / Alohan'ny", "Sur la partie antérieure.", "Il se tient devant la maison.", "Mijoro eo alohan'ny trano izy."),
    ("Derrière", "prép.", "Aorian'ny", "Sur la partie postérieure.", "Le jardin est derrière le bâtiment.", "Ao aorian'ny trano ny jardina."),
    ("Entre", "prép.", "Antsangan'ny / Anelanelan'ny", "Dans l'espace séparant deux choses.", "Le village est situé entre deux collines.", "Ao anelanelan'ny tendrombohitra roa ny tanàna."),
    ("Pour", "prép.", "Ho an'i / Mba", "Indique la destination ou le but.", "Ce cadeau est pour toi.", "Ho anao ity meva ity."),
    ("Par", "prép.", "Amin'ny / Am-", "Indique le moyen ou le lieu de passage.", "Nous passons par Tamatave.", "Mampitaha any Toamasina izahay."),
    ("Pendant", "prép.", "Mandritra ny", "Durant un espace de temps.", "Pendant les vacances, nous voyagerons.", "Mandritra ny fialan-tsasatra, hitety tany izahay."),
    ("Car", "conj.", "Sady / Satria", "Car indique la cause.", "Je reste car il pleut.", "Mijanona aho satria avy ny rainay."),
    ("Mais", "conj.", "Sady izany / Saingy", "Marque l'opposition.", "Il est petit mais très fort.", "Kely izy saingy mafy be."),
    ("Ou", "conj.", "Na", "Marque le choix.", "Café ou thé ?", "Kafe na thé ?"),
    ("Et", "conj.", "Sy", "Marque l'addition.", "Du riz et du poisson.", "Vary sy hazandrano."),
    ("Donc", "conj.", "Koa / Izany hoe", "Marque la conséquence.", "Je pense donc je suis.", "Mieritreritra aho koa maha-izy aho."),
    ("Parce que", "locution", "Satria", "Donne la raison.", "Je suis content parce que tu es là.", "Faly aho satria eto ianao."),
    ("Pourquoi", "adv.", "Nahoana", "Demande la cause.", "Pourquoi ries-tu ?", "Nahoana ianao no mihomehy ?"),
    ("Comment", "adv.", "Mahoana / Ahoana", "Demande la manière.", "Comment allez-vous ?", "Mahoana ianao ?"),
    ("Quand", "adv.", "Roviana / Rahoviana", "Demande le moment.", "Quand partez-vous ?", "Rahoviana ianao no hiala ?"),
    ("Où", "adv.", "Aiza", "Demande le lieu.", "Où habitez-vous ?", "Aiza no monina ianao ?"),
    ("Qui", "pron.", "Iza", "Désigne une personne.", "Qui est à la porte ?", "Iza no eo am-varavarana ?")
]
