items = [
    ("Tête", "n.f.", "Loha", "Partie supérieure du corps humain.", "J'ai mal à la tête depuis ce matin.", "Marary loha aho hatramin'izao maraina izao."),
    ("Yeux", "n.m.pl.", "Maso", "Organes de la vue.", "Ses yeux sont brillants.", "Mifantsika ny masony."),
    ("Nez", "n.m.", "Orona", "Organe de l'odorat au milieu du visage.", "Le nez permet de respirer.", "Manampy amin'ny fise respirer ny orona."),
    ("Bouche", "n.f.", "Vava", "Ouverture du visage pour manger et parler.", "Ouvrez la bouche pour l'examen.", "Sokafy ny vava amin'ny fizahana."),
    ("Oreille", "n.f.", "Tsofina", "Organe de l'ouïe.", "J'entends une musique avec mes oreilles.", "Mihaino mozika amin'ny tsofinako aho."),
    ("Bras", "n.m.", "Sandry", "Membre supérieur.", "Il lève les bras au ciel.", "Mano ho ambony ny sandry izy."),
    ("Main", "n.f.", "Tanana", "Extrémité du bras.", "Lave-toi les mains avant le repas.", "Sasao ny tananao alohan'ny sakafo."),
    ("Doigt", "n.m.", "Rantsan-tanana", "Chacune des extrémités de la main.", "Il s'est coupé le doigt.", "Nisokatra ny rantsan-tanany."),
    ("Jambe", "n.f.", "Tomboka / Hamsy", "Membre inférieur.", "Mes jambes sont fatiguées après la marche.", "Mavandy ny tomboko aorian'ny fandehanana."),
    ("Pied", "n.m.", "Tongotra", "Extrémité de la jambe.", "Je marche à pied tous les jours.", "Mandeha amin'ny tongotra aho hatrany."),
    ("Cœur", "n.m.", "Fo", "Organe qui fait circuler le sang.", "Le cœur bat régulièrement.", "Miopa am-pimonina ny fo."),
    ("Estomac", "n.m.", "Kibo / Estomac", "Organe de la digestion.", "Mon estomac est vide.", "Gana ny kiboko."),
    ("Sang", "n.m.", "Ra", "Liquide rouge circulant dans les veines.", "Le sang apporte l'oxygène.", "Manome oxigène ny ra."),
    ("Maladie", "n.f.", "Aretina", "Altération de la santé.", "La prévention évite les maladies.", "Manakana aretina ny fitandremana."),
    ("Douleur", "n.f.", "Fanaintainana", "Sensation pénible.", "Où localisez-vous la douleur ?", "Aiza no tsapanao ny fanaintainana ?"),
    ("Dentiste", "n.m.", "Mpitsabo nify", "Spécialiste des soins dentaires.", "Le dentiste soigne la carie.", "Mitsabo ny nify marary ny mpitsabo nify."),
    ("Malade", "adj.", "Marary", "Qui souffre d'une maladie.", "Il est malade et reste au lit.", "Marary izy ka mijanona ao am-pandriana."),
    ("Blessure", "n.f.", "Faratra", "Lésion faite au corps.", "La blessure guérit bien.", "Mihagagana tsara ny faratra."),
    ("Pansement", "n.m.", "Pansement / Lamba fantsana", "Bande pour protéger une plaie.", "Mettez un pansement propre.", "Asio pansement madio."),
    ("Visage", "n.m.", "Tava", "Partie antérieure de la tête.", "Un grand sourire illumine son visage.", "Mifantsika amin'ny tavany ny tsiky."),
    ("Cheveux", "n.m.pl.", "Volo", "Poils de la tête.", "Elle a les cheveux longs.", "Lava volo izy."),
    ("Dent", "n.f.", "Nify", "Organe dur dans la bouche pour mâcher.", "Brosse tes dents deux fois par jour.", "Brosio fa indray roa amin'ny andro ny nify."),
    ("Langue", "n.f.", "Lela", "Organe gustatif et de la parole.", "Tirez la langue s'il vous plaît.", "Atsaharo ny lela azafady."),
    ("Dos", "n.m.", "Lamosina", "Partie postérieure du tronc.", "J'ai mal au dos ce soir.", "Marary lamosina aho izao hariva izao."),
    ("Genou", "n.m.", "Lohalika", "Articulation entre la cuisse et la jambe.", "Il s'est fait mal au genou.", "Nivoaka ny lohaliny."),
    ("Épaule", "n.f.", "Soroka", "Articulation du bras au tronc.", "Il porte son sac sur l'épaule.", "Mitondra sakosy amin'ny soroka izy."),
    ("Poitrine", "n.f.", "Tratra", "Partie antérieure du buste.", "Respirez fort par la poitrine.", "Mifantsiha amin'ny tratra."),
    ("Ventre", "n.m.", "Kibo", "Partie inférieure de l'abdomen.", "J'ai trop mangé, j'ai mal au ventre.", "Be sakafo loatra aho, marary kibo."),
    ("Peut", "n.f.", "Kibon-doha / Hoditra", "Enveloppe extérieure du corps.", "Protéger sa peau du soleil.", "Atsaharo amin'ny masoandro ny hoditra."),
    ("Urgence", "n.f.", "Maimaim-poana / Urgence", "Situation nécessitant une intervention rapide.", "Appelez les urgences immédiatement !", "Antsoy ny urgence avy hatrany !")
]
