items = [
    ("Maison", "n.f.", "Trano", "Bâtiment servant d'habitation.", "La maison est très grande.", "Tena lehibe ny trano."),
    ("Chambre", "n.f.", "Efitrano", "Pièce destinée au sommeil.", "Ma chambre est au premier étage.", "Ao amin'ny rihana voalohany ny efitranoko."),
    ("Cuisine", "n.f.", "Lalantsaka / Trano fikarakarana sakafo", "Pièce où l'on prépare la nourriture.", "Elle cuisine dans la cuisine.", "Mahandro ao an-dakozia izy."),
    ("Salon", "n.m.", "Trano fandraisam-bahiny", "Pièce principale pour recevoir.", "Nous regardons la télévision au salon.", "Mijery televiziona ao an-trano fandraisam-bahiny izahay."),
    ("Lit", "n.m.", "Rihana / Fandriana", "Meuble sur lequel on dort.", "Le lit est très confortable.", "Tena mahafinaritra ny fandriana."),
    ("Table", "n.m.", "Latabatra", "Meuble composé d'un plateau posé sur des pieds.", "Mettez le plat sur la table.", "Atsaharo amin'ny latabatra ny lovia."),
    ("Chaise", "n.f.", "Sazana / Seza", "Siège à dossier sans bras.", "Asseyez-vous sur cette chaise.", "Mhipetraha amin'ity seza ity."),
    ("Porte", "n.f.", "Varavarana", "Ouverture permettant d'entrer.", "Fermez la porte s'il vous plaît.", "Akatony ny varavarana azafady."),
    ("Fenêtre", "n.f.", "Varavarankely", "Ouverture pratiquée dans un mur pour donner du jour.", "Ouvrez la fenêtre pour aérer.", "Sokafy ny varavarankely mba hidiran'ny rivotra."),
    ("Toit", "n.m.", "Tafon-trano", "Couverture d'un bâtiment.", "Le toit est couvert de tôles.", "Rakotry ny bati ny tafon-trano."),
    ("Jardin", "n.m.", "Jardina / Saha", "Terrain où l'on cultive des fleurs ou légumes.", "Il y a de belles fleurs dans le jardin.", "Misy voninkazo tsara ao an-jaridaina."),
    ("Mur", "n.m.", "Rindrina", "Ouvrage en maçonnerie servant à clore.", "Le mur est peint en blanc.", "Lokoina fotsy ny rindrina."),
    ("Clé", "n.f.", "Fanalahidy", "Instrument servant à fermer ou ouvrir une serrure.", "J'ai perdu ma clé de maison.", "Lasa ny fanalahidiko ny trano."),
    ("Miroir", "n.m.", "Fitaratra", "Surface réfléchissant la lumière et les images.", "Elle se regarde dans le miroir.", "Mijery tena ao amin'ny fitaratra izy."),
    ("Armoire", "n.f.", "Kabine / Armoire", "Meuble de rangement muni de portes.", "Rrange tes vêtements dans l'armoire.", "Alamino ao amin'ny armoire ny akanjonao."),
    ("Refrigérateur", "n.m.", "Frigo / Fampangatsiahana", "Appareil ménager gardant les aliments au frais.", "Mets le lait au réfrigérateur.", "Atsaharo ao amin'ny frigo ny ronono."),
    ("Lampe", "n.f.", "Jiro", "Appareil d'éclairage.", "Allume la lampe de bureau.", "Mampirefeta ny jiro latabatra."),
    ("Douche", "n.f.", "Fandroana", "Installation pour se laver le corps.", "Je prends une douche chaude.", "Mandro amin'ny rano mafana aho."),
    ("Électricité", "n.f.", "Rano-jiro / Angovo", "Forme d'énergie d'éclairage et force.", "L'électricité est coupée ce soir.", "Tapaka ny jiro izao hariva izao."),
    ("Télévision", "n.m.", "Televiziona", "Appareil de réception des programmes audiovisuels.", "Les enfants regardent la télévision.", "Mijery televiziona ny ankizy."),
    ("Radio", "n.f.", "Radio", "Appareil d'émission ou réception sonore.", "J'écoute les nouvelles à la radio.", "Mihaino vaovao amin'ny radio aho."),
    ("Tapis", "n.m.", "Tsihy / Tapis", "Ouvrage textile recouvrant le sol.", "Le tapis est très doux.", "Tena malemy ilay tapis."),
    ("Escalier", "n.m.", "Lalantsara / Escalier", "Suite de marches servant à monter ou descendre.", "Montez l'escalier jusqu'au deuxième étage.", "Miakaraha amin'ny escalier hatreny amin'ny rihana faharoa."),
    ("Canapé", "n.m.", "Canapé / Seza lava", "Siège confortable pour plusieurs personnes.", "Installons-nous sur le canapé.", "Mhipetraha eo amin'ny canapé isika."),
    ("Couverture", "n.f.", "Rai-mandry / Deho", "Pièce d'étoffe chaude pour le lit.", "La couverture est très chaude.", "Tena mafana ny couverture."),
    ("Oreiller", "n.m.", "Oron-doha / Ondana", "Coussin pour poser la tête au lit.", "Pose ta tête sur l'oreiller.", "Atsaharo amin'ny ondana ny lohanao."),
    ("Assiette", "n.f.", "Lovia", "Récipient individuel pour manger.", "Lave ton assiette après le repas.", "Sasao ny loviaio aorian'ny sakafo."),
    ("Verre", "n.m.", "Vera", "Récipient transparent pour boire.", "Remplis ce verre d'eau.", "Fenoina rano ity vera ity."),
    ("Cuillère", "n.f.", "Sotro", "Ustensile creux pour manger la soupe.", "Mange ta soupe avec la cuillère.", "Hano amin'ny sotro ny sabao."),
    ("Fourchette", "n.f.", "Fourchette / Sotro rantsana", "Ustensile à dents pour pique la nourriture.", "Utilise la fourchette pour la viande.", "Ampiasao ny fourchette amin'ny hena."),
    ("Couteau", "n.m.", "Antsy", "Ustensile servant à couper.", "Attention, ce couteau coupe fort.", "Mitandrema, maranitra be io antsi io."),
    ("Casserole", "n.f.", "Vilany", "Récipient de cuisine à manche.", "Fais chauffer l'eau dans la casserole.", "Mano mafana rano ao an-vilany."),
    ("Poêle", "n.f.", "Kandra / Poêle", "Ustensile plat pour frire.", "Fais cuire les œufs dans la poêle.", "Endaso ao an-poêle ny atody."),
    ("Bouteille", "n.f.", "Tavoahangy", "Récipient à col étroit.", "Apporte une bouteille d'eau.", "Ento ny tavoahangy rano."),
    ("Tasse", "n.f.", "Kopy / Tasse", "Petit récipient avec anse pour boissons chaudes.", "Je bois une tasse de café.", "Misotro tasse café aho."),
    ("Serviette", "n.f.", "Servieta", "Linge pour s'essuyer.", "Essuie-toi avec la serviette propre.", "Lamao amin'ny servieta madio izao."),
    ("Savon", "n.m.", "Savony", "Produit utilisé pour se laver.", "Lave-toi les mains avec du savon.", "Sasao amin'ny savony ny tananao."),
    ("Brosse", "n.f.", "Brossy", "Ustensile à poils pour nettoyer.", "Brosse tes dents après le repas.", "Brosio ny nifinao aorian'ny sakafo."),
    ("Robinet", "n.m.", "Lomisy / Robinet", "Appareil réglant le débit d'un liquide.", "Ferme bien le robinet d'eau.", "Akatony tsara ny robinet rano."),
    ("Poubelle", "n.f.", "Gony fako / Poubelle", "Récipient pour les déchets.", "Jette l'emballage dans la poubelle.", "Ario ao an-poubelle ny fonosana.")
]
