items = [
    ("Chien", "n.m.", "Alika", "Animal domestique fidèle.", "Le chien garde la maison.", "Miantoka ny trano ny alika."),
    ("Chat", "n.m.", "Saka", "Petit félin domestique.", "Le chat dort sur la chaise.", "Matory eo amin'ny seza ny saka."),
    ("Zébu", "n.m.", "Omby", "Bovin à bosse emblématique de Madagascar.", "Le zébu tire la charrette.", "Mitarika ny kalesy ny omby."),
    ("Poule", "n.f.", "Akoho vavy", "Volaille pondeuse.", "La poule pond des œufs chaque jour.", "Mano atody indray amin'ny andro ny akoho vavy."),
    ("Oiseau", "n.m.", "Vorona", "Animal à plumes et à ailes.", "L'oiseau chante dans l'arbre.", "Mihira ao an-kazo ny vorona."),
    ("Lémurien", "n.m.", "Maki / Gidro", "Primate endémique de Madagascar.", "Le maki vit dans la forêt tropicale.", "Monina ao an'ala ny maki."),
    ("Arbre", "n.m.", "Kazo", "Végétal à tronc boisueux.", "Cet arbre produit des fruits sucrés.", "Manome voankazo mamy io kazo io."),
    ("Fleur", "n.f.", "Voninkazo", "Partie colorée des plantes.", "La fleur sent très bon.", "Tena manitra ny voninkazo."),
    ("Forêt", "n.f.", "Ala", "Grande étendue couverte d'arbres.", "La forêt protège la biodiversité.", "Miantoka ny ala ny zavaboary."),
    ("Rivière", "n.f.", "Rano-mandry / Ony / Rano", "Cours d'eau naturel.", "Les enfants se baignent dans la rivière.", "Mandro ao an-rano ny ankizy."),
    ("Mer", "n.f.", "Rano-masina", "Vaste étendue d'eau salée.", "La mer est calme aujourd'hui.", "Milamina ny rano-masina androany."),
    ("Plage", "n.f.", "Bord de mer / Plage", "Bord de mer couverte de sable.", "Les touristes marchent sur la plage.", "Mandeha ao am-plage ny mpitsidika."),
    ("Montagne", "n.m.", "Mendrika / Tendrombohitra", "Relief très élevé du sol.", "La montagne est couverte de brume.", "Rakotry ny zavona ny tendrombohitra."),
    ("Lune", "n.f.", "Volana", "Astre éclairant la nuit.", "La pleine lune brille fort.", "Mifantsika be ny volana feno."),
    ("Étoile", "n.f.", "Kintana", "Astre brillant dans le ciel nocturne.", "Les étoiles scintillent dans la nuit.", "Mifantsika amin'ny alina ny kintana."),
    ("Terre", "n.f.", "Tany", "Planète où nous vivons ou sol.", "La terre est fertile.", "Mahafinaritra ny tany."),
    ("Pierre", "n.f.", "Vato", "Matière minérale dure.", "Le mur est construit en pierres.", "Amboarina amin'ny vato ny rindrina."),
    ("Sable", "n.m.", "Ratsy tany / Fasika", "Petits grains minéraux du sol ou de la plage.", "Les enfants jouent dans le sable.", "Milalao amin'ny fasika ny ankizy."),
    ("Lac", "n.m.", "Farihy", "Grande étendue d'eau entourée de terre.", "Le lac Mantasoa est magnifique.", "Tena kanto ny farihy Mantasoa."),
    ("Île", "n.f.", "Nosy", "Terre entourée d'eau.", "Nosy Be est une île très visitée.", "Nosy be mpitsidika i Nosy Be."),
    ("Plante", "n.f.", "Zavamaniry", "Organisme végétal.", "Arrose les plantes du jardin.", "Manondraha rano ny zavamaniry."),
    ("Feuille", "n.f.", "Ravina", "Partie verte des végétaux.", "Les feuilles de l'arbre tombent.", "Mihintsana ny ravin-kazo."),
    ("Branche", "n.f.", "Rantsan-kazo", "Partie de l'arbre portant les feuilles.", "L'oiseau se pose sur la branche.", "Mhipetraha amin'ny rantsan-kazo ny vorona."),
    ("Lion", "n.m.", "Lions / Liona", "Grand félin sauvage.", "Le lion est le roi de la savane.", "Mpanjakan'ny savane ny liona."),
    ("Cheval", "n.m.", "Soavaly", "Grand mammifère équidé.", "Il monte à cheval avec élégance.", "Mitaingina soavaly amin'ny fomba tsara izy."),
    ("Vache", "n.f.", "Omby vavy", "Femelle du zébu ou taureau.", "La vache donne du bon lait.", "Manome ronono tsara ny omby vavy."),
    ("Cochon", "n.m.", "Kisoa", "Animal domestique élevé pour sa viande.", "Le cochon vit dans la porcherie.", "Monina ao an-kisoa ny kisoa."),
    ("Chèvre", "n.f.", "Osy", "Animal ruminant à cornes.", "L'osy broute l'herbe sur la colline.", "Mihinana ahitra amin'ny tendrombohitra ny osy."),
    ("Mouton", "n.m.", "Odrilala / Ondry", "Animal élevé pour sa laine.", "Le berger garde le troupeau d'ondry.", "Miantoka ny ondry ny mpiandry."),
    ("Crocodile", "n.m.", "Mamba / Voay", "Grand reptile aquatique.", "Le voay vit dans le fleuve Betsiboka.", "Monina ao Betsiboka ny voay.")
]
