items = [
    ("Jour", "n.m.", "Andro", "Période de 24 heures.", "Passez un très bon jour.", "Manana andro finaritra be ianao."),
    ("Nuit", "n.f.", "Alina", "Période d'obscurité entre le coucher et le lever du soleil.", "Bonne nuit et doux rêves.", "Tsara alina ary mirary nofy tsara."),
    ("Matin", "n.m.", "Maraina", "Début de la journée.", "Le matin, le soleil se lève.", "Miposaka ny andro amin'ny maraina."),
    ("Soir", "n.m.", "Hariva", "Fin de la journée.", "Nous nous voyons ce soir.", "Mifankahita isika izao hariva izao."),
    ("Midi", "n.m.", "Atoandro", "Douze heures de la journée.", "Il est midi, allons déjeuner.", "Atoandro ny andro, andeha hisakafo."),
    ("Minuit", "n.m.", "Mio-alina", "Douze heures de la nuit.", "Le train arrive à minuit.", "Maha-avy amin'ny mio-alina ny train."),
    ("Minute", "n.f.", "Minitra", "Unité de temps égale à soixante secondes.", "Attendez une minute s'il vous plaît.", "Andraso iray minitra azafady."),
    ("Seconde", "n.f.", "Sokondra / Segondra", "Soixantième partie d'une minute.", "Chaque seconde compte.", "Manana ny lanjany ny segondra tsirairay."),
    ("Semaine", "n.f.", "Herinandro", "Période de sept jours consécutifs.", "À la semaine prochaine !", "Hita amin'ny herinandro ambony !"),
    ("Mois", "n.m.", "Volana", "Douzième partie de l'année.", "Le mois de mai est très agréable.", "Tena mahafinaritra ny volana Mey."),
    ("Année", "n.f.", "Taona", "Période de douze mois.", "Bonne nouvelle année à tous !", "Tratry ny taona vaovao ianareo rehetra !"),
    ("Hier", "adv.", "Omaly", "Le jour précédant aujourd'hui.", "Hier, il a plu toute la journée.", "Omaly, avy ny rainay tontolo andro."),
    ("Lundi", "n.m.", "Alatsinainy", "Premier jour de la semaine.", "Le lundi, l'école reprend.", "Manomboka ny sekoly amin'ny Alatsinainy."),
    ("Mardi", "n.m.", "Talata", "Deuxième jour de la semaine.", "Mardi est le jour du marché.", "Andro tsena ny Talata."),
    ("Mercredi", "n.m.", "Alarobia", "Troisième jour de la semaine.", "Le mercredi après-midi est libre.", "Malalaka ny Alarobia atoandro."),
    ("Jeudi", "n.m.", "Alakamisy", "Quatrième jour de la semaine.", "Jeudi, j'ai un rendez-vous.", "Manana fotoana aho amin'ny Alakamisy."),
    ("Vendredi", "n.m.", "Zoma", "Cinquième jour de la semaine.", "Vendredi soir, c'est le week-end.", "Handeha week-end ny Zoma hariva."),
    ("Samedi", "n.m.", "Sabotsy", "Sixième jour de la semaine.", "Le samedi, nous faisons du sport.", "Manao spora izahay amin'ny Sabotsy."),
    ("Dimanche", "n.m.", "Alahady", "Septième jour de la semaine.", "Le dimanche est un jour de repos.", "Andro fialan-tsasatra ny Alahady."),
    ("Janvier", "n.m.", "Janoary", "Premier mois de l'année.", "Janvier marque le début de l'année.", "Manomboka ny taona ny Janoary."),
    ("Février", "n.m.", "Febroary", "Deuxième mois de l'année.", "Février est le mois le plus court.", "Fohy indrindra ny volana Febroary."),
    ("Mars", "n.m.", "Martsa", "Troisième mois de l'année.", "En mars, le printemps approche.", "Manatona ny printemps amin'ny Martsa."),
    ("Avril", "n.m.", "Aprily", "Quatrième mois de l'année.", "En avril, ne te découvre pas d'un fil.", "Aza manary lamba amin'ny Aprily."),
    ("Mai", "n.m.", "Mey", "Cinquième mois de l'année.", "Le mois de mai est ensoleillé.", "Maimaim-poana ny andro amin'ny Mey."),
    ("Juin", "n.m.", "Jona", "Sixième mois de l'année.", "Les examens ont lieu en juin.", "Atao amin'ny Jona ny fanadinana."),
    ("Juillet", "n.m.", "Jolay", "Septième mois de l'année.", "Juillet est le mois des vacances.", "Volana fialan-tsasatra ny Jolay."),
    ("Août", "n.m.", "Aogositra", "Huitième mois de l'année.", "Août est très chaud.", "Mafana be ny Aogositra."),
    ("Septembre", "n.m.", "Septambra", "Neuvième mois de l'année.", "La rentrée a lieu en septembre.", "Atao amin'ny Septambra ny fampidirana sekoly."),
    ("Octobre", "n.m.", "Oktobra", "Dixième mois de l'année.", "En octobre, les feuilles tombent.", "Mihintsana ny ravina amin'ny Oktobra."),
    ("Novembre", "n.m.", "Novambra", "Onzième mois de l'année.", "Novembre est souvent pluvieux.", "Matetika avy ny rainay amin'ny Novambra."),
    ("Décembre", "n.m.", "Desambra", "Douzième mois de l'année.", "Noël est célébré en décembre.", "Karakaraina amin'ny Desambra ny Noely."),
    ("Printemps", "n.m.", "Lohataona", "Saison du renouveau de la nature.", "Les fleurs éclosent au printemps.", "Mamelana ny voninkazo amin'ny lohataona."),
    ("Été", "n.m.", "Pahavaratra / fahavaratra", "Saison chaude et pluvieuse à Madagascar.", "L'été est la saison des pluies.", "Pahavaratra ny andro fahavaratra."),
    ("Automne", "n.m.", "Fararano", "Saison de la récolte.", "L'automne est la saison de la récolte du riz.", "Fararano ny fiotazana vary."),
    ("Hiver", "n.m.", "Ririnina", "Saison froide.", "L'hiver à Antsirabe est très frais.", "Mangatsiaka be ny ririnina any Antsirabe."),
    ("Soleil", "n.m.", "Masoandro", "Astre éclairant la terre.", "Le soleil brille fort aujourd'hui.", "Mifantsika be ny masoandro androany."),
    ("Pluie", "n.f.", "Rainay / Orana", "Eau tombant des nuages.", "La pluie rafraîchit l'atmosphère.", "Mampangatsiatsiaka ny andro ny orana."),
    ("Vent", "n.m.", "Rivotra", "Déplacement d'air.", "Le vent souffle très fort.", "Mifantsika mafy ny rivotra."),
    ("Nuage", "n.m.", "Rano-rahona / Rahona", "Masse de vapeur d'eau suspendue.", "Le ciel est couvert de nuages.", "Rakotry ny rahona ny ciel."),
    ("Orage", "n.m.", "Hagandra / Tadio", "Perturbation atmosphérique avec éclairs.", "Un grand orage éclate ce soir.", "Misy tadio lehibe izao hariva izao."),
    ("Ciel", "n.m.", "Lanitra", "Espace bleu au-dessus de nous.", "Le ciel est dégagé et bleu.", "Madio sy manga ny lanitra.")
]
