items = [
    ("Avoir", "v.", "Manana", "Posséder quelque chose.", "J'ai un livre intéressant.", "Manana boky mahaliana aho."),
    ("Être", "v.", "Maha-izy / Aho / Misy", "Exister ou caractériser.", "Je suis très heureux aujourd'hui.", "Faly be aho androany."),
    ("Boire", "v.", "Misotro", "Avaler un liquide.", "Il boit de l'eau fraîche.", "Misotro rano mangatsiaka izy."),
    ("Parler", "v.", "Miteny / Miresaka", "Exprimer des idées par la parole.", "Nous parlons français et malgache.", "Miteny frantsay sy malagasy izahay."),
    ("Écouter", "v.", "Mihaino", "Prêter attention aux sons.", "J'écoute la radio le matin.", "Mihaino radio maraina aho."),
    ("Voir", "v.", "Mahita", "Percevoir par les yeux.", "Je vois la mer au loin.", "Mahita rano-masina any lavitra aho."),
    ("Regarder", "v.", "Mijery", "Fixer ses yeux sur quelque chose.", "Ils regardent un film.", "Mijery film izy ireo."),
    ("Dormir", "v.", "Matory", "Reposer son corps pendant la nuit.", "Le bébé dort huit heures.", "Matory valo ora ny zazakely."),
    ("Marcher", "v.", "Mandeha", "Se déplacer à pied.", "Nous marchons dans la forêt.", "Mandeha ao an'ala izahay."),
    ("Courir", "v.", "Mihazakazaka", "Se déplacer très rapidement à pied.", "Il court pour attraper le bus.", "Mihazakazaka izy hisambotra ny bus."),
    ("Travailler", "v.", "Miasa", "Effectuer un travail.", "Elle travaille dans un bureau.", "Miasa ao an-biro izy."),
    ("Étudier", "v.", "Mianatra", "Acquérir des connaissances.", "Les étudiants étudient la gestion.", "Mianatra gestion ny mpianatra."),
    ("Aimer", "v.", "Tia", "Éprouver de l'affection ou du goût.", "J'aime la musique malgache.", "Tia mozika malagasy aho."),
    ("Vouloir", "v.", "Mila / Te-...", "Avoir le désir de quelque chose.", "Je veux apprendre le français.", "Te-hianatra teny frantsay aho."),
    ("Pouvoir", "v.", "Afaka", "Avoir la capacité de faire.", "Vous pouvez entrer maintenant.", "Afaka miditra ianao izao."),
    ("Devoir", "v.", "Tsy maintsy", "Avoir l'obligation de faire.", "Je dois partir tôt.", "Tsy maintsy miala maraina aho."),
    ("Aller", "v.", "Mandeha / Handeha", "Se rendre dans un lieu.", "Je vais au marché.", "Handeha any an-tsena aho."),
    ("Venir", "v.", "Avy / Tonga", "Se déplacer vers ici.", "Il vient chez nous ce soir.", "Avy ao aminay izy izao hariva izao."),
    ("Faire", "v.", "Mano / Manao", "Réaliser ou accomplir une action.", "Que fais-tu aujourd'hui ?", "Inona no ataonao androany ?"),
    ("Prendre", "v.", "Maka / Mampiasa", "Saisir ou utiliser.", "Je prends un café.", "Maka kafe aho."),
    ("Donner", "v.", "Manome", "Accorder ou transmettre quelque chose.", "Donne-moi ta main.", "Omeo ahy ny tananao."),
    ("Demander", "v.", "Monompo / Mangataka", "Solliciter une réponse ou aide.", "Il demande le chemin.", "Mangataka ny lálana izy."),
    ("Répondre", "v.", "Mamaly", "Donner une réponse.", "Répondez à la question.", "Valio ny fanontaniana."),
    ("Chercher", "v.", "Mikaroka / Mitady", "Tenter de trouver.", "Je cherche mes clés.", "Mitady ny fanalahidiko aho."),
    ("Trouver", "v.", "Mahita", "Découvrir ce qu'on cherchait.", "J'ai trouvé une solution.", "Nahita solution aho."),
    ("Penser", "v.", "Mieritreritra", "Exercer son esprit.", "Je pense à mon avenir.", "Mieritreritra ny ho aviko aho."),
    ("Connaître", "v.", "Mahafantatra", "Avoir la notion de quelqu'un ou quelque chose.", "Je connais bien cette ville.", "Mahafantatra tsara ity tanàna ity aho."),
    ("Écrire", "v.", "Manoratra", "Tracer des signes de langage.", "Elle écrit un e-mail.", "Manoratra e-mail izy."),
    ("Lire", "v.", "Mamaky", "Déchiffrer un texte.", "Je lis un journal.", "Mamaky journal aho."),
    ("Apprendre", "v.", "Mianatra / Mahazo", "Acquérir un savoir.", "J'apprends le malgache.", "Mianatra teny malagasy aho."),
    ("Vendre", "v.", "Mivarotra", "Céder contre de l'argent.", "Il vend des légumes au marché.", "Mivarotra legioma ao an-tsena izy."),
    ("Choisir", "v.", "Mifidy", "Sélectionner parmi plusieurs.", "Choisissez votre plat préféré.", "Fidilizo ny sakafo tianao indrindra."),
    ("Ouvrir", "v.", "Sokafana / Manokatra", "Rendre accessible.", "Ouvrez la porte.", "Sokafy ny varavarana."),
    ("Fermer", "v.", "Akatona / Manakatona", "Obstruer une ouverture.", "Fermez la fenêtre.", "Akatony ny varavarankely."),
    ("Commencer", "v.", "Manomboka", "Débuter une action.", "La réunion commence.", "Manomboka ny fivoriana."),
    ("Finir", "v.", "Mano izao / Mamarana", "Arriver au terme.", "Nous finissons le travail.", "Mamarana ny asa izahay."),
    ("Attendre", "v.", "Miandry", "Rester jusqu'à l'arrivée de quelqu'un.", "J'attends le bus.", "Miandry bus aho."),
    ("Partir", "v.", "Miala", "S'en aller d'un lieu.", "Le train part à neuf heures.", "Miala amin'ny sivy ora ny lamasinina."),
    ("Arriver", "v.", "Tonga", "Parvenir à destination.", "Nous sommes arrivés à la maison.", "Tonga ao an-trano izahay."),
    ("Entrer", "v.", "Miditra", "Passer du dehors au dedans.", "Entrez s'il vous plaît.", "Miditra azafady."),
    ("Sortir", "v.", "Mivoaka", "Passer du dedans au dehors.", "Il sort de la pièce.", "Mivoaka ny efitrano izy."),
    ("Rester", "v.", "Mijanona", "Demeurer au même endroit.", "Je reste à la maison ce soir.", "Mijanona ao an-trano aho izao hariva izao."),
    ("Vivre", "v.", "Mivelona / Monina", "Être en vie ou habiter.", "Ils vivent paisiblement.", "Monina am-pimonina izy ireo."),
    ("Changer", "v.", "Manova", "Rendre différent.", "Le temps change vite.", "Manova haingana ny andro."),
    ("Mettre", "v.", "Atsaharo / Manao", "Placer ou porter.", "Mets ton chapeau.", "Manoa satroka."),
    ("Jouer", "v.", "Milalao", "S'amuser à un jeu.", "Les enfants jouent au ballon.", "Milalao baolina ny ankizy."),
    ("Chanter", "v.", "Mihira", "Former des sons musicaux avec la voix.", "Elle chante une belle chanson.", "Mihira hira tsara izy."),
    ("Danser", "v.", "Mandihy", "Exécuter des pas en rythme.", "Nous dansons pendant la fête.", "Mandihy izahay amin'ny fety."),
    ("Cuisiner", "v.", "Mahandro", "Préparer le repas.", "Mon père cuisine le dimanche.", "Mahandro amin'ny Alahady ny raiko."),
    ("Laver", "v.", "Manasa", "Nettoyer avec de l'eau.", "Lave tes mains.", "Sasao ny tananao."),
    ("Nettoyer", "v.", "Manadio", "Rendre propre.", "Il nettoie sa chambre.", "Manadio ny efitranony izy."),
    ("Porter", "v.", "Mitondra / Mano", "Soutenir ou revêtir.", "Il porte un sac lourd.", "Mitondra sakosy mavandy izy."),
    ("Conduire", "v.", "Mpanamory / Mitondra fiara", "Diriger un véhicule.", "Elle conduit prudemment.", "Mitondra fiara amin'ny fitandremana izy."),
    ("Voyager", "v.", "Mitety tany / Mandeha dia", "Faire un voyage.", "J'aime voyager en avion.", "Tia mitety tany amin'ny roplanina aho."),
    ("Aider", "v.", "Manampy", "Apporter son concours.", "Pouvez-vous m'aider ?", "Afaka manampy ahy ve ianao ?"),
    ("Expliquer", "v.", "Manazava", "Rendre clair une idée.", "Le maître explique la leçon.", "Manazava ny lesona ny mpampianatra."),
    ("Montrer", "v.", "Maneho / Mampiseho", "Faire voir quelque chose.", "Montrez-moi le chemin.", "Aseho ahy ny lálana."),
    ("Se souvenir", "v.", "Mahatadidy", "Garder en mémoire.", "Je me souviens de ce jour.", "Mahatadidy io andro io aho."),
    ("Oublier", "v.", "Manadino", "Ne pas se rappeler.", "N'oublie pas tes clés.", "Aza adino ny fanalahidinao."),
    ("Espérer", "v.", "Manantena", "Considérer comme probable et souhaitable.", "J'espère que tout ira bien.", "Manantena aho fa handeha tsara ny rehetra.")
]
