items = [
    ("Bureau", "n.m.", "Biro", "Lieu de travail administratif.", "Mon bureau est situé au centre-ville.", "Ao an-tsena ny biroko."),
    ("Prix", "n.m.", "Vidiny", "Valeur d'une chose exprimée en argent.", "Quel est le prix de cet article ?", "Mahoana ny vidin'ity zavatra ity ?"),
    ("Salaire", "n.m.", "Karama", "Rémunération du travail.", "Le salaire est versé en fin de mois.", "Atsaharo amin'ny faran'ny volana ny karama."),
    ("Chef", "n.m.", "Mpanompo / Lehibe", "Personne qui dirige.", "Le chef d'entreprise anime la réunion.", "Manentana ny fivoriana ny lehiben'ny orinasa."),
    ("Employé", "n.m.", "Mpiasa", "Personne travaillant contre un salaire.", "L'employé répond au téléphone.", "Mamaly finday ny mpiasa."),
    ("Métier", "n.m.", "Asa / Profession", "Activité professionnelle.", "Enseignant est un beau métier.", "Asa tsara ny fampianarana."),
    ("Commerce", "n.m.", "Barotra / Fivoriana varotra", "Activité d'achat et de vente.", "Le commerce fleurit dans la région.", "Miroso ny barotra ao an-toerana."),
    ("Vente", "n.f.", "Fivarotana", "Action de vendre.", "La vente commence à neuf heures.", "Manomboka amin'ny sivy ora ny fivarotana."),
    ("Achat", "n.m.", "Fividianana", "Action d'acheter.", "Faites vos achats au marché.", "Atao ao an-tsena ny fividianana."),
    ("Contrat", "n.m.", "Fifสัญญา / Fifanarahana", "Accord officiel signé.", "Signez le contrat de travail.", "Soniavo ny fifanarahana asa."),
    ("Client", "n.m.", "Mpanjifa", "Acheteur de biens ou services.", "Le client demande un renseignement.", "Monompo fampahalalana ny mpanjifa."),
    ("Compte", "n.m.", "Kaonto", "Enregistrement financier bancaire.", "J'ai ouvert un compte bancaire.", "Nanokatra kaonto banky aho."),
    ("Facture", "n.f.", "Facture / Taratasy fandoavam-bola", "Document comptable attestant un achat.", "Demandez la facture au vendeur.", "Monompo facture amin'ny mpivarotra."),
    ("Paiement", "n.m.", "Fandoavam-bola", "Règlement d'une somme due.", "Le paiement s'effectue en liquide.", "Amin'ny cash no fandoavam-bola."),
    ("Monnaie", "n.f.", "Vola madinika", "Pièces de monnaie.", "Avez-vous de la monnaie ?", "Manana vola madinika ve ianao ?"),
    ("Économie", "n.f.", "Toekarena", "Ensemble des activités de production.", "L'économie nationale se développe.", "Miroso ny toekarena nasionaly."),
    ("Directeur", "n.m.", "Talen-sekoly / Tale", "Personne dirigeant un établissement.", "Le directeur approuve le projet.", "Maneho fankatoavana ny tale."),
    ("Collègue", "n.m.", "Mpiara-miasa", "Personne travaillant dans le même lieu.", "Je m'entends très bien avec mes collègues.", "Mifankahazo tsara amin'ny mpiara-miasa aho."),
    ("Emploi", "n.m.", "Asa / Toerana", "Poste de travail occupé.", "Il cherche un emploi stable.", "Mila asa mafy izy."),
    ("Budget", "n.m.", "Teti-bola", "Prévision des recettes et dépenses.", "Le budget annuel est validé.", "Maneho fankatoavana ny teti-bola."),
    ("Impôt", "n.m.", "Hetra", "Contribution financière obligatoire.", "Chaque citoyen paie l'impôt.", "Mandoa hetra ny olompirenena tsirairay."),
    ("Crédit", "n.m.", "Mbola / Crédit", "Prêt d'argent consenti.", "La banque m'a accordé un crédit.", "Nomena crédit amin'ny banky aho."),
    ("Bénéfice", "n.m.", "Tombony", "Gain financier réalisé.", "L'entreprise a fait un bon bénéfice.", "Nahazo tombony tsara ny orinasa."),
    ("Perte", "n.f.", "Fatiantoka", "Diminution de valeur ou manque à gagner.", "Éviter les pertes inutiles.", "Manakana fatiantoka tsy ilaina."),
    ("Investissement", "n.m.", "Fampiasam-bola", "Placement de capital.", "Un investissement rentable.", "Fampiasam-bola mahafinaritra."),
    ("Boutique", "n.f.", "Fivarotana", "Lieu où l'on vend.", "La boutique propose des promotions.", "Manolotra promotion ny fivarotana."),
    ("Patron", "n.m.", "Mpanompo / Lehibe", "Chef d'entreprise.", "Le patron félicite l'équipe.", "Manome fisaorana ny lehibe."),
    ("Équipe", "n.f.", "Karakara / Ekipa", "Groupe travaillant ensemble.", "Notre équipe a réussi le projet.", "Nahomby tamin'ny tetikasa ny ekipantsika."),
    ("Rapport", "n.m.", "Taratasy mpanazava / Rapport", "Document décrivant une situation.", "Rédiger le rapport de réunion.", "Manoratra rapport fivoriana."),
    ("Stage", "n.m.", "Fiofanana / Stage", "Période de formation pratique.", "L'étudiant fait un stage en entreprise.", "Mano fiofanana ao an-orinasa ny mpianatra.")
]
