const fs = require('fs');
const path = require('path');

// Base 34 words
const baseWords = [
  { "word": "Bonjour", "type": "interj.", "translation": "Manao ahoana (maraina/andro)", "definition": "Formule de salutation polie utilisée pendant la journée.", "example_fr": "Bonjour, comment allez-vous ?", "example_mg": "Manao ahoana, manao ahoana ny fahasalamanao ?" },
  { "word": "Merci", "type": "interj.", "translation": "Misaotra", "definition": "Expression de la gratitude ou du remerciement.", "example_fr": "Merci beaucoup pour votre aide.", "example_mg": "Misaotra betsaka amin'ny fanampianao." },
  { "word": "S'il vous plaît", "type": "locution", "translation": "Azafady", "definition": "Formule de politesse pour demander quelque chose.", "example_fr": "Un verre d'eau, s'il vous plaît.", "example_mg": "Rano iray vera, azafady." },
  { "word": "Argent", "type": "n.m.", "translation": "Vola", "definition": "Moyen d'échange, pièces ou billets de banque.", "example_fr": "Je n'ai pas assez d'argent.", "example_mg": "Tsy manana vola ampy aho." },
  { "word": "Marché", "type": "n.m.", "translation": "Tsena", "definition": "Lieu public où l'on vend et achète des marchandises.", "example_fr": "Je vais au marché acheter des fruits.", "example_mg": "Handeha any an-tsena hividy voankazo aho." },
  { "word": "Travail", "type": "n.m.", "translation": "Asa", "definition": "Activité professionnelle rémunérée.", "example_fr": "Il aime son travail à Antananarivo.", "example_mg": "Tia ny asany any Antananarivo izy." },
  { "word": "Manger", "type": "v.", "translation": "Mihinana", "definition": "Prendre de la nourriture pour s'alimenter.", "example_fr": "Nous allons manger ensemble ce midi.", "example_mg": "Hiaraka hisakafo isika anio antoandro." },
  { "word": "Ami", "type": "n.", "translation": "Namana", "definition": "Personne avec qui l'on a une relation d'affection.", "example_fr": "C'est mon meilleur ami.", "example_mg": "Izy no namako akaiky indrindra." },
  { "word": "E-mail", "type": "n.m.", "translation": "Taratasy elektronika (e-mail)", "definition": "Courrier électronique échangé sur un réseau informatique.", "example_fr": "Je vous ai envoyé un e-mail ce matin.", "example_mg": "Nalefako e-mail ianao izao maraina izao." },
  { "word": "Projet", "type": "n.m.", "translation": "Tetikasa", "definition": "Idée ou plan élaboré pour réaliser une action future.", "example_fr": "Notre projet avance très bien.", "example_mg": "Miroso tsara ny tetikasantsika." },
  { "word": "Entreprise", "type": "n.f.", "translation": "Orinasa / Barotra", "definition": "Organisation économique produisant des biens ou services.", "example_fr": "L'entreprise embauche de nouveaux diplômés.", "example_mg": "Mampiditra mpiasa diplaoma vaovao ny orinasa." },
  { "word": "Chambre", "type": "n.f.", "translation": "Efitrano", "definition": "Pièce d'une habitation destinée au logement ou au sommeil.", "example_fr": "J'ai réservé une chambre pour deux nuits.", "example_mg": "Namandrika efitrano ho an'ny roa alina aho." },
  { "word": "Hôtel", "type": "n.m.", "translation": "Hotely", "definition": "Établissement commercial qui offre un hébergement payant.", "example_fr": "L'hôtel se trouve près du centre-ville.", "example_mg": "Ao akaikin'ny afovoan-tànana ny hotely." },
  { "word": "Voyage", "type": "n.m.", "translation": "Dia", "definition": "Déplacement que l'on fait d'un lieu à un autre éloigné.", "example_fr": "Bon voyage à Antsirabe !", "example_mg": "Tafatsangana soa amin'ny dia mankany Antsirabe!" },
  { "word": "Pharmacie", "type": "n.f.", "translation": "Farmasia / Trano fanafody", "definition": "Officine où l'on prépare et vend des médicaments.", "example_fr": "La pharmacie est ouverte même le dimanche.", "example_mg": "Misokatra na amin'ny Alahady aza ny farmasia." },
  { "word": "Médecin", "type": "n.m.", "translation": "Mpitsabo / Dokotera", "definition": "Professionnel de santé habilité à diagnostiquer et traiter les maladies.", "example_fr": "Le médecin a prescrit un sirop pour la toux.", "example_mg": "Nomen'ny dokotera siro ho an'ny kohaka izy." },
  { "word": "Fièvre", "type": "n.f.", "translation": "Sondro-panethana / Mafana", "definition": "Élévation de la température du corps au-dessus de la normale.", "example_fr": "L'enfant a un peu de fièvre.", "example_mg": "Mafana kely ny zaza." },
  { "word": "Voiture", "type": "n.f.", "translation": "Fiara", "definition": "Véhicule automobile servant au transport des personnes.", "example_fr": "Nous voyageons en voiture de location.", "example_mg": "Mitety tany amin'ny fiara hofaina izahay." },
  { "word": "Riz", "type": "n.m.", "translation": "Vary", "definition": "Céréale constituant l'aliment de base à Madagascar.", "example_fr": "Le riz est servi à chaque repas.", "example_mg": "Misy vary hatrany amin'ny sakafo rehetra." },
  { "word": "Eau", "type": "n.f.", "translation": "Rano", "definition": "Liquide transparent indispensable à la vie.", "example_fr": "Apportez une bouteille d'eau minerale.", "example_mg": "Ento ny tavoahangy rano mineraly." },
  { "word": "Maison", "type": "n.f.", "translation": "Trano", "definition": "Bâtiment servant d'habitation aux personnes.", "example_fr": "La maison est située près de la grande route.", "example_mg": "Miorina akaikin'ny lálana lehibe ny trano." },
  { "word": "Famille", "type": "n.f.", "translation": "Fianakaviana", "definition": "Ensemble des personnes unies par des liens de parenté.", "example_fr": "Toute la famille se réunit le dimanche.", "example_mg": "Mivory ny fianakaviana iray manontolo amin'ny Alahady." },
  { "word": "Téléphone", "type": "n.m.", "translation": "Finday", "definition": "Appareil de communication sans fil ou fixe.", "example_fr": "Mon téléphone n'a plus de batterie.", "example_mg": "Tsy misy vato intsony ny findaiko." },
  { "word": "Livre", "type": "n.m.", "translation": "Boky", "definition": "Assemblage de feuilles imprimées formant un ouvrage.", "example_fr": "J'ai emprunté un livre à la bibliothèque.", "example_mg": "Nindrana boky ao amin'ny trano famakiam-boky aho." },
  { "word": "École", "type": "n.f.", "translation": "Sekoly", "definition": "Établissement où l'on dispense l'enseignement.", "example_fr": "Les enfants vont à l'école le matin.", "example_mg": "Mandeha any an-tsekoly maraina ny ankizy." },
  { "word": "Aujourd'hui", "type": "adv.", "translation": "Androany", "definition": "Le jour présent dans lequel nous sommes.", "example_fr": "Quel est le programme pour aujourd'hui ?", "example_mg": "Inona no fandaharana ho an'androany?" },
  { "word": "Demain", "type": "adv.", "translation": "Ampitso", "definition": "Le jour immédiatement après aujourd'hui.", "example_fr": "Le rendez-vous est fixé pour demain matin.", "example_mg": "Karakaraina ho ampitso maraina ny fotoana." },
  { "word": "Heure", "type": "n.f.", "translation": "Ora / Fotoana", "definition": "Unité de mesure du temps égale à soixante minutes.", "example_fr": "À quelle heure commence la réunion ?", "example_mg": "Amin'ny firy ora no manomboka ny fivoriana?" },
  { "word": "Route", "type": "n.f.", "translation": "Lálana", "definition": "Voie de communication carrossable aménagée hors des agglomérations.", "example_fr": "La route nationale est très fréquentée.", "example_mg": "Be mpampiasa ny lálana nasionaly." },
  { "word": "Réunion", "type": "n.f.", "translation": "Fivoriana", "definition": "Rassemblement de personnes pour discuter d'un sujet.", "example_fr": "La réunion débutera à neuf heures précises.", "example_mg": "Hanonboka amin'ny tsara amin'ny sivy ora ny fivoriana." },
  { "word": "Fichier", "type": "n.m.", "translation": "Rakitra / Dosie", "definition": "Ensemble d'informations numérisées enregistrées sur un support.", "example_fr": "Je vous envoie le fichier par e-mail.", "example_mg": "Alefako e-mail aminao ny rakitra." },
  { "word": "Acheter", "type": "v.", "translation": "Mividy / Hividy", "definition": "Acquérir un bien ou service contre paiement.", "example_fr": "Je vais acheter du pain au marché.", "example_mg": "Handeha hividy mofo any an-tsena aho." },
  { "word": "Payer", "type": "v.", "translation": "Mandoa vola", "definition": "Donner de l'argent en échange d'un bien ou d'un service.", "example_fr": "Vous pouvez payer par carte bancaire ou en espèces.", "example_mg": "Afaka mandoa vola amin'ny karatra na amin'ny vola tanana ianao." },
  { "word": "Comprendre", "type": "v.", "translation": "Mahazo / Mazava", "definition": "Saisir le sens de quelque chose par l'esprit.", "example_fr": "Est-ce que vous comprenez la phrase en malgache ?", "example_mg": "Azonao ve ny fehezanteny amin'ny teny malagasy?" }
];

console.log("Building 1000 words dataset script...");
